### ISSUE TITLE
[Epic] Add Models in CUDA Benchmark Focus Suite to IREE Benchmarking System

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12873]
### Request description

We have defined a set of models to monitor and make progress on. This issue tracks work involved in adding these models to the IREE Benchmarking System.

**Tensorflow**

ResNet50
- [x] Inference, FP32, Batch Sizes 1, 8, 64, 128, 256, 2048

Bert-Large
- [x] Inference, FP32, Batch Sizes 1, 16, 24, 32, 48, 64, 512, 1024, 1280
- [ ] Training. Workloads TBD.

T5-Large
- [x] Inference, FP32, Batch Size 1, 16, 24, 32, 48, 64, 512

DLRM
- [ ] Inference, FP32, Batch Sizes 51.2k, 65.5k, 200k, 262.1k, 263k, 274k, 315k, 334k

**PyTorch**

ResNet50
- [x] Inference, FP32, Batch Sizes 1, 8, 64, 128, 256, 2048
- [x] Inference, FP16, Batch Sizes 1, 8, 64, 128, 256, 2048

Bert-Large
- [x] Inference, FP32, Batch Sizes 1, 16, 24, 32, 48, 64, 512, 1024, 1280
- [x] Inference, FP16, Batch Sizes 1, 16, 24, 32, 48, 64, 512, 1024, 1280
- [ ] Training. Workloads TBD.

T5-Large
- [ ] Inference, FP32, Batch Size 1, 16, 24, 32, 48, 64, 512
* Error lowering to MLIR (https://github.com/llvm/torch-mlir/issues/1977)
- [ ] Inference, FP16, Batch Size 1

DLRM
- [ ] Inference, FP32, Batch Sizes 51.2k, 65.5k, 200k, 262.1k, 263k, 274k, 315k, 334k
- [ ] Inference, FP16, Batch Sizes 51.2k, 65.5k, 200k, 262.1k, 263k, 274k, 315k, 334k

**JAX**

ResNet50
- [x] Inference, FP32, Batch Sizes 1, 8, 64, 128, 256, 2048
- [ ] Inference, BF16, Batch Sizes 1, 8, 64, 128, 256, 2048

Bert-Large
- [x] Inference, FP32, Batch Sizes 1, 16, 24, 32, 48, 64, 512, 1024, 1280
- [ ] Inference, BF16, Batch Sizes 1, 16, 24, 32, 48, 64, 512, 1024, 1280
- [ ] Training. Workloads TBD.

T5-Large
- [x] Inference, FP32, Batch Size 1, 16, 24, 32, 48, 64, 512
- [ ] Inference, BF16, Batch Size 1, 16, 24, 32, 48, 64, 512

DLRM
- [ ] Inference, FP32, Batch Sizes 51.2k, 65.5k, 200k, 262.1k, 263k, 274k, 315k, 334k
- [ ] Inference, BF16, Batch Sizes 51.2k, 65.5k, 200k, 262.1k, 263k, 274k, 315k, 334k

GPT-3
- [ ] Training, FP32, Global batch size 1536 over 768 replicas.
- [ ] Training, BF16, Global batch size 1536 over 768 replicas.

AlphaFold 2
- [ ] Inference, FP32, Batch Size 1

**Comment by mariecwhite** [comment]
GPT-3 Training owner: @phoenix-meadowlark 
Alphafold 2 Inference owner: @silvasean

**Comment by allieculp** [comment]
@mariecwhite Is this in progress? Would like to update the status if so!

**Comment by mariecwhite** [comment]
Yep, in progress.

**Comment by allieculp** [comment]
@mariecwhite Taking Epic updates on a weekly basis - let us know if any news here or just WIP? Target for these Epics is end of Q2.

**Comment by mariecwhite** [comment]
I've updated the description with what has been implemented. We now have TF and PyTorch ResNet50, Bert-Large and T5-Large models running in OOBI for IREE CUDA. XLA:GPU currently in progress.

**Comment by allieculp** [comment]
@mariecwhite Any updates on this Epic?

**Comment by mariecwhite** [comment]
The list itself is evolving. Some high level changes:

- We'll pare back on the number of FP16 models needed. There isn't a straightforward way to generate FP16 models in TF so we'll remove that and use FP16 models in JAX and PyTorch. BF16 is also top of mind so we'll add models with this datatype once compiler support is online.
- We're adding FLAX pretrained models to the mix. Specifically, BERT and T5.
- @phoenix-meadowlark is making progress on GPT-3 training and has it running locally.
- Deepmind models have been de-prioritized.
- We expect to add more LLMs into the suite with eventual support for multi-gpu.

**Comment by mariecwhite** [comment]
I updated the list of models in the Issue description to include JAX models and BF16. We are making progress on adding JAX inference FP32 models and @reichlfl will have some FP16 Torch models ready in the next week.

**Comment by mariecwhite** [comment]
We now have JAX models running for XLA:GPU and IREE.

**Comment by allieculp** [comment]
@mariecwhite Is this still relevant?

**Comment by mariecwhite** [comment]
We can close this.
