### ISSUE TITLE
[Epic] Support collective ops in OpenXLA and PJRT Client

### ISSUE THREAD

**Issue by julianwa** [iree-org/iree#12930]
```[tasklist]
### Tasks
- [x] https://github.com/openxla/iree/issues/12931 
- [x] https://github.com/openxla/iree/issues/12695
- [ ] https://github.com/openxla/iree/issues/13262 
- [ ] https://github.com/openxla/iree/issues/12932
- [ ] https://github.com/openxla/iree/issues/12946 
- [ ] https://github.com/openxla/iree/issues/12947 
- [ ] https://github.com/openxla/iree/issues/12948 
- [ ] https://github.com/openxla/iree/issues/13100
- [x] https://github.com/openxla/iree/issues/13101 
- [ ] Improved JAX -> PJRT client option passing (dep on JAX team)
- [ ] https://github.com/openxla/iree/issues/13628
```
