### ISSUE TITLE
[Epic] Determine workflows for profiling JAX -> IREE + CUDA

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#13145]
Tracking issue for trying/improving/documenting "end to end" developer workflows taking programs written in JAX, compiling them through IREE, and then profiling the runtime execution of that compiled code using IREE tools, vendor tools, etc.

Specific areas of focus (somewhat driven by project prioritization and customer needs):
* CUDA compiler + runtime
* Large programs (where the compiler's point of view with "dispatch regions" may be far from the user's point of view with "layers", "modules", "ops", and other Python/JAX concepts)
* Source location plumbing (how much do we currently track? is all of it used in our tooling?)

```[tasklist]
### Related tasks:
- [ ] https://github.com/openxla/iree/issues/5454
- [ ] https://github.com/openxla/iree/issues/13142
- [ ] https://github.com/openxla/iree/issues/13570
- [ ] Expand on developer [profiling documentation](https://github.com/openxla/iree/blob/main/docs/developers/developing_iree/profiling.md)
```

**Comment by jpienaar** [comment]
Would be great if this worked via openxla-pjrt-plugin :)

(source locations should be rather good, I know @hawkinsp had mentioned they dropped some as no consumer could show it yet)

**Comment by allieculp** [comment]
@ScottTodd @mattwalsh Just checking that this is in the right place, is this a P1 Epic for MS2? We didn't have this on our list before, but can certainly be added.

I'm going to add my name to assignees just so I can keep track of Epics!

**Comment by allieculp** [comment]
@ScottTodd Looking to update our Epic level items - can you give a brief update here?

**Comment by ScottTodd** [comment]
Tracy can now show executable sources when using the Vulkan and CUDA HAL drivers.

I've also started ramping up on using JAX. So far I've run some sample programs with `@jax.jit` and `JAX_DUMP_IR_TO` then tried to feed the JIT'd IR to IREE tools. I'm looking to see if the python source locations captured there will also show up in Tracy (without the location snapshoting done by `--iree-hal-dump-executable-sources-to={path}`).

Once I have some workflow propped up, I want to make a pass through our JAX documentation and samples, since we're really sparse in that area right now

They will likely be further work to correlate parts of input programs with runtime traces (in Tracy or vendor tools like NVIDIA Nsight).

**Comment by allieculp** [comment]
Hey @ScottTodd, just doing the weekly check-in here. Any update?

**Comment by ScottTodd** [comment]
Yep, I mentioned this issue in https://github.com/openxla/iree/pull/13500. With that, Python source locations will be shown in Tracy (executable source locations are already shown when you use `--iree-hal-dump-executable-sources-to={path}`). I expect that will help when profiling, but some workflows will still be awkward and difficult (especially if you want to look across fusions and other compilation details).

As expected, I want to write some JAX documentation and/or samples next.

**Comment by silvasean** [comment]
Ideally IREE could produce data in the format needed for the tools in https://jax.readthedocs.io/en/latest/profiling.html to light up. (actually JAX users will probably insist on that, since presumably this is an existing workflow for them). At least from my perspective more on the user side, it makes more sense to me to work on this than on Tracy-based tooling.

**Comment by benvanik** [comment]
Part of the work of making the tracing support pluggable is to allow PJRT to provide its own tracing sink - it can do whatever it wants then. Someone working on that project will be able to wire it up in a way that makes sense for them.

**Comment by allieculp** [comment]
@ScottTodd Is this still relevant?

**Comment by ScottTodd** [comment]
Probably relevant to someone, but it's at least not a priority for me right now. I'd vote to close and then re-open as needed.
