### ISSUE TITLE
[Epic][CPU] Enable predictable performance for matrix multiplication using data-tiling and micro-kernels

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#13216]
This EPIC tracking all the micro-kernel related work.

### Tasks related to core functionality.

```[tasklist]
- [x] Enable use of microkernel through plugins
- [x] Enable use of microkernels through bitcode linking (#12112 ) : WIP PR : #13460
- [ ] Benchmark performance on models of data tiling approach using microkernels as plugins (until #12112 is addressed)
- [ ] #11360
- [ ] Avoid needing to unpack the results of the GEMM, by writing results of GEMM in unpacked form
- [ ] Improve distribution of CPU code-generation to threads.
- [ ] https://github.com/openxla/iree/issues/14431
```

### Blocking issues with data-tiling on e2e workloads

```[tasklist]
- [ ] https://github.com/openxla/iree/issues/14414
- [ ] https://github.com/openxla/iree/issues/14398
- [ ] https://github.com/openxla/iree/issues/14252
```

### Amortizing costs related to packing/unpacking by using propagation

```[tasklist]
### Tasks
- [ ] Add a early matmul -> data tiling pass to preprocessing stage
- [ ] Add DataLayoutPropagation pass to preprocessing or flow stage
```

#### Enable propagation in models where packing can be done without padding, starting with MobileBertfp32.

Some supports are already developed in -[upstream](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Linalg/Transforms/DataLayoutPropagation.cpp). To enable it for MobileBert, we need

```[tasklist]
### Tasks
- [ ] #13530 
- [ ] #13531 
- [ ] #13532 
```

#### Evaluating propagation in models where packing needs padding as well.

This needs more investigation. Propagation of tensor.pack ops with padding values is very challenging. We are able to propagate it through some limited cases. Need more investigation for this part.
