### ISSUE TITLE
[Epic][CPU] Improve code generation infrastructure

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#13220]
Task list:
- [ ] https://github.com/openxla/iree/issues/12926
- [ ] [P1] Support CPUs in micro-kernel generation tool.
- [ ] [P2] Add support for AMD uProf.
- [ ] [P2] Add pass to flag vector/unrolling sizes that are too large.

**Comment by powderluv** [comment]
AMD uProf would be nice
