### ISSUE TITLE
[Epic] CUDA HAL driver rewrite for production

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13245]
### Background 

The current CUDA HAL driver was prototyped in the early days and have implementation details rendering production usage hard. To name a few big ones: [full stream synchronization](https://github.com/openxla/iree/blob/60b623ab29738219345306b37d760207262b9e2d/runtime/src/iree/hal/drivers/cuda/cuda_device.c#L533-L540) after each queue execute, [no HAL semaphore](https://github.com/openxla/iree/blob/60b623ab29738219345306b37d760207262b9e2d/runtime/src/iree/hal/drivers/cuda/cuda_device.c#L551-L556) support, [no stream-ordered allocation](https://github.com/openxla/iree/blob/60b623ab29738219345306b37d760207262b9e2d/runtime/src/iree/hal/drivers/cuda/cuda_device.c#L473-L501) support, [linear nodes in CUDA graph](https://github.com/openxla/iree/blob/60b623ab29738219345306b37d760207262b9e2d/runtime/src/iree/hal/drivers/cuda/graph_command_buffer.c#L640-L642),  [tightly integrated context wrapper](https://github.com/openxla/iree/blob/60b623ab29738219345306b37d760207262b9e2d/runtime/src/iree/hal/drivers/cuda/context_wrapper.h#L14-L21) making it hard to support multi queue/device. There are also various other smaller issues, like [tightly coupled CUDA and NCCL symbols](https://github.com/openxla/iree/blob/60b623ab29738219345306b37d760207262b9e2d/runtime/src/iree/hal/drivers/cuda/dynamic_symbols.h#L22-L36) hindering optionality, etc.

### Goals and Plans
We would need to rewrite portions of the CUDA HAL driver and modernize others accordingly to better implement IREE HAL abstractions and support future production use cases. Concretely, we would like the CUDA HAL driver to:

* Support **async workload submission** for better GPU utilization
* Implement **proper HAL semaphore** for host/device <-> host/device synchronization
* **Stream-ordered allocation** to sequence allocations and compute
* Implement HAL command buffers with **CUDA graph**s for low launch overhead
* Factor in **multi queue/device** in various APIs to not limit the support

The above, if done properly, should make supporting multi queue/device training/inference and interleaving different CUDA library/CodeGen solutions and even external systems approaches easier.

Note that this doesn't concern the kernel and executable side much. There are places we can improve there too; but those are largely detachable and can happen separately.

The overall plan is to start a new experimental HAL driver in [experiemental/](https://github.com/openxla/iree/tree/main/experimental), `cuda2`, and pull in pieces from existing CUDA HAL driver when suitable, and improve and land incrementally. 

### Concrete Tasks

These are major abstract tasks now; as we go we'll break them down into smaller ones and create seprate task list to track.

```[tasklist]
### Basics
- [ ] https://github.com/openxla/iree/pull/13942
- [ ] https://github.com/openxla/iree/pull/13955
- [ ] https://github.com/openxla/iree/pull/14011
- [ ] https://github.com/openxla/iree/pull/14063
- [ ] https://github.com/openxla/iree/issues/13250 
- [ ] Document this CUDA HAL driver and its relationship with other ecosystem components
```

```[tasklist]
### Memory Management
- [ ] https://github.com/openxla/iree/pull/13985
- [ ] https://github.com/openxla/iree/pull/13440
```

```[tasklist]
### Compute Pipeline
- [ ] https://github.com/openxla/iree/pull/14038
- [ ] https://github.com/openxla/iree/pull/14062
- [ ] https://github.com/openxla/iree/pull/14326
- [ ] https://github.com/openxla/iree/pull/14524
- [ ] https://github.com/openxla/iree/pull/14525
- [ ] https://github.com/openxla/iree/pull/14526
- [ ] https://github.com/openxla/iree/pull/15325
- [ ] https://github.com/openxla/iree/pull/14857
- [ ] https://github.com/openxla/iree/pull/15423
```

```[tasklist]
### Synchronization
- [ ] https://github.com/openxla/iree/pull/14325
- [ ] https://github.com/openxla/iree/issues/4727
```

```[tasklist]
### Collectives
- [ ] https://github.com/openxla/iree/pull/14059
```

**Comment by allieculp** [comment]
@julianwa @antiagainst @mattwalsh @benvanik I believe this is still in Lei's queue, please update if any progress has been made.

**Comment by allieculp** [comment]
@julianwa @mattwalsh @antiagainst Noting here, this may need to be bumped up in priority before end of Q2.

**Comment by julianwa** [comment]
@antiagainst when do you expect the metal back-end to land? I assume that it would be poor choice to start this prior to that. I'm just seeing what the earliest timeframe to start this is -- without considering the other work you have planned for Q2 for the moment.

**Comment by antiagainst** [comment]
I'm under the impression that the CUDA HAL rewrite is scheduled to start at Q3. I'm expecting to finish up and land the Metal HAL impl by end of this month. So earliest we can start is June.

**Comment by antiagainst** [comment]
I've updated the title and fleshed out some of the goals and plans in the issue, after discussing with @benvanik. This is not final and we'll  continue refine the details as we go.

**Comment by antiagainst** [comment]
https://github.com/openxla/iree/pull/14620 moves the already functional `cuda2` impl to `hal/drivers`, to wire up BUILD configurations and enable integration and testing before final replacing the existing CUDA impl. Major tasks before final migration:

* Port over `CUstream`-based command buffer to make it feature parity with the existing impl (_blocking_)
* Duplicate/replace various correctness tests to use `cuda2` and adress potential failures (_blocking_)
* Duplicate/replace various benchmark tests to use `cuda2` and address potential regressions (_blocking_)
* [After some time..]
* Delete `cuda` and rename `cuda2` as `cuda`

**Comment by antiagainst** [comment]
https://github.com/openxla/iree/pull/14620 landed; now `cuda2` is in `hal/drivers`. Next, we need:

* Replace various tests/benchmarks in-tree to use cuda2 and address potential issues
* [After bing stable of some time..]
* Delete `cuda` and rename `cuda2` as `cuda`

Also sent https://groups.google.com/g/iree-discuss/c/q2_HgHmGma0 to the group.

**Comment by antiagainst** [comment]
#16107 switches the new cuda2 impl on by default. Following up work is to delete cuda1 code and rename cuda2 symbols to cuda, but not blocking, so this issue is marked as closed now.
