### ISSUE TITLE
[Epic][CPU] Scalable (SVE) and dynamic (RVV) vectorization support in MLIR and IREE CPU pipeline

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#13334]
On the scalable side, this would entail:

- [x] Sending an RFC to inform the community about the proposal and next steps
- [x] Adding support for scalable vectors to the tiling and vectorization constructs in the Transform dialect
- [ ] Adding support for scalable vectors to IREE’s tiling infrastructure
- [ ] Adding support for scalable vectors to vector masking representation (vector.mask) and lowering
- [ ] Adding support for scalable vectors to the Linalg vectorizer
- [ ] Adding missing support for scalable vectors (if any) to rest of the lowering passes after vectorization

On the dynamic side, this would entail:

- [ ] Sending an RFC about the dynamic vector representation in MLIR
- [ ] Adding support for the dynamic vector representation and lowering
- [ ] Moving vector.mask to the new representation (if applicable)
- [ ] Adding support for dynamic vectors to the Linalg vectorizer
- [ ] Adding missing support (if any) to rest of the lowering passes after vectorization
- [ ] Adding support for dynamic vectors to IREE’s tiling infrastructure
- [ ] Adding missing support for dynamic vectors (if any) to rest of the lowering passes after vectorization

**Comment by dcaballe** [comment]
(@banach-space, for visibility)

**Comment by sequencer** [comment]
@dcaballe Is this PR still in deprecate state? I think this should be a important feature which can significantly provides much more optimization opportunity for both SVE2 and RVV.

**Comment by banach-space** [comment]
Hey @sequencer — AFAIK, Diego is no longer working on this. However, there has been a lot of progress on supporting scalable vectors. We're getting quite close to fully supporting data tiling for scalable vectors, which was the main outstanding item.

As for dynamic vectors (relevant only to RVV), that discussion doesn’t seem to be progressing, AFAIK. Here's the most recent RFC:

* https://discourse.llvm.org/t/rfc-dynamic-vector-semantics-for-the-mlir-vector-dialect/

If you're interested in scalable vectors, feel free to reach out — I’d be happy to chat about it! Or anything else related to MLIR vectors and CPUs :)

-Andrzej

**Comment by sequencer** [comment]
Thanks @banach-space!
Actually we are also using the [buddy-compiler](https://github.com/buddy-compiler/buddy-mlir/) for lowering the pytorch to native RISC-V Vector, author of buddy-compiler is the also the author of the rfc ;p

And we successfully run it on our embedded RISC-V Vector implementations, [here](https://github.com/chipsalliance/t1/tree/master/tests/pytorch) is our use cases.

We wanna also support it in the IREE framework to support some of our end-users, we are not sure appending the dynamic vector to IREE or waiting for its upstream to LLVM.

**Comment by banach-space** [comment]
> We wanna also support it in the IREE framework to support some of our end-users, we are not sure appending the dynamic vector to IREE or waiting for its upstream to LLVM.

Based on the previous discussion, I wouldn't expect support for dynamic vectors in upstream LLVM any time soon. But that's just my interpretation. As for IREE, it would be best to reach out active IREE contributors directly:
* https://github.com/iree-org/iree?tab=readme-ov-file#communication-channels

Thanks!

**Comment by sequencer** [comment]
Thank you!
cc @FantasqueX I think this should be the first milestone which we can contribute to IREE!
cc @bhbruce @ElEHsiang, is possible for you to evaluate and review our dynamic vector dialect support in the future?
