### ISSUE TITLE
[Epic] IREE Dispatch Profiler

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13494]
Issues strictly concerning IREE dispatch profiler. 

```[tasklist]
### Tasks
- [x] #13281 
- [x] #13290 
- [ ] #12899
- [ ] #13086
- [ ] #13461
- [x] #13463
- [ ] #13495
```

```[tasklist]
## Tuning Related Tasks (Related to https://github.com/openxla/iree/issues/13417)
- [ ] python bindings support
- [ ] add argument support for data_type, batch_dim, and custom configuration
- [ ] type annotations (nice to have)
```

**Comment by allieculp** [comment]
@manishucsd I am auditing some old issues - is this still relevant?
