### ISSUE TITLE
Improve tensor.pack x86 codegen for unaligned cases

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#13524]
We'll use 16x16 shuffle approach for packing LHS soon, which is a transposition op. That only works for aligned cases because
1. tensor.pack op decomposition only works for static shapes.
2. tensor.pad vectorization is not efficient.
 
We need to decompose dynamic tensor.pack ops (i.e, dynamic outer shapes, but static inner tile sizes); vectorize dynamic tensor.pad ops (which are bounded by tiling sizes).

```[tasklist]
### Tasks
- [x] Supporting 16x16 specialized transpose lowering for AVX512 targets
- [x] Add support for lowerPack op on dynamic shapes
- [x] Enable vector masking for tensor.pad ops on static shapes
```

**Comment by hanhanW** [comment]
Input IR:

```mlir
func.func @dynamic_pack(%9: tensor<?x?xf32>) -> tensor<?x?x16x1xf32>{
  %c16 = arith.constant 16 : index
  %c1 = arith.constant 1 : index
  %c0 = arith.constant 0 : index
  %cst = arith.constant 0.000000e+00 : f32

  %d0 = tensor.dim %9, %c0 : tensor<?x?xf32>
  %d1 = tensor.dim %9, %c1 : tensor<?x?xf32>

  %tiled_d0 = arith.ceildivui %d0, %c16 : index
  %tiled_d1 = arith.ceildivui %d1, %c1 : index
  %8 = tensor.empty(%tiled_d0, %tiled_d1) : tensor<?x?x16x1xf32>

  %pack = tensor.pack %9 padding_value(%cst : f32) inner_dims_pos = [0, 1] inner_tiles = [16, 1] into %8 : tensor<?x?xf32> -> tensor<?x?x16x1xf32>
  return %pack : tensor<?x?x16x1xf32>
}
```

This is the IR we want to vectorize for single unaligned pack op:

```mlir
func.func @dynamic_pack_dispatch_0() {
  %c16 = arith.constant 16 : index
  %c1 = arith.constant 1 : index
  %cst = arith.constant 0.000000e+00 : f32
  %c0 = arith.constant 0 : index
  %0 = hal.interface.constant.load[0] : i32
  %1 = hal.interface.constant.load[1] : i32
  %2 = hal.interface.constant.load[2] : i32
  %3 = arith.index_castui %0 : i32 to index
  %4 = arith.index_castui %1 : i32 to index
  %5 = arith.index_castui %2 : i32 to index
  %6 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<?x?xf32>>{%3, %5}
  %7 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<?x?x16x1xf32>>{%4, %5}
  %workgroup_id_x = hal.interface.workgroup.id[0] : index
  %workgroup_count_x = hal.interface.workgroup.count[0] : index
  %workgroup_id_y = hal.interface.workgroup.id[1] : index
  %workgroup_count_y = hal.interface.workgroup.count[1] : index
  %8 = affine.apply affine_map<()[s0] -> (s0 * 4)>()[%workgroup_id_y]
  %9 = affine.apply affine_map<()[s0] -> (s0 * 4)>()[%workgroup_count_y]
  scf.for %arg0 = %8 to %4 step %9 {
    %10 = affine.min affine_map<(d0)[s0] -> (-d0 + s0, 4)>(%arg0)[%4]
    %11 = affine.apply affine_map<()[s0] -> (s0 * 64)>()[%workgroup_id_x]
    %12 = affine.apply affine_map<()[s0] -> (s0 * 64)>()[%workgroup_count_x]
    scf.for %arg1 = %11 to %5 step %12 {
      %13 = affine.min affine_map<(d0)[s0] -> (-d0 + s0, 64)>(%arg1)[%5]
      %14 = flow.dispatch.tensor.load %7, offsets = [%arg0, %arg1, 0, 0], sizes = [%10, %13, 16, 1], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<writeonly:tensor<?x?x16x1xf32>>{%4, %5} -> tensor<?x?x16x1xf32>
      %15 = affine.min affine_map<(d0, d1)[s0] -> (d1 * -16 + s0, d0 * 16)>(%10, %arg0)[%3]
      %16 = affine.apply affine_map<(d0) -> (d0 * 16)>(%arg0)
      %17 = flow.dispatch.tensor.load %6, offsets = [%16, %arg1], sizes = [%15, %13], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<?x?xf32>>{%3, %5} -> tensor<?x?xf32>
      %18 = scf.for %arg2 = %c0 to %10 step %c1 iter_args(%arg3 = %14) -> (tensor<?x?x16x1xf32>) {
        %19 = scf.for %arg4 = %c0 to %13 step %c16 iter_args(%arg5 = %arg3) -> (tensor<?x?x16x1xf32>) {
          %20 = affine.min affine_map<(d0)[s0] -> (-d0 + s0, 16)>(%arg4)[%13]
          %21 = affine.apply affine_map<(d0) -> (d0 * 16)>(%arg2)
          %22 = affine.min affine_map<(d0, d1) -> (16, d0 - d1 * 16)>(%15, %arg2)
          %23 = affine.min affine_map<(d0, d1)[s0] -> (-d1 + s0, 16, d0 - d1)>(%13, %arg4)[%13]
          %extracted_slice = tensor.extract_slice %17[%21, %arg4] [%22, %23] [1, 1] : tensor<?x?xf32> to tensor<?x?xf32>
          %extracted_slice_0 = tensor.extract_slice %arg5[%arg2, %arg4, 0, 0] [1, %20, 16, 1] [1, 1, 1, 1] : tensor<?x?x16x1xf32> to tensor<1x?x16x1xf32>
          %24 = affine.apply affine_map<(d0) -> (-d0 + (d0 ceildiv 16) * 16)>(%22)
          %padded = tensor.pad %extracted_slice low[0, 0] high[%24, 0] {
          ^bb0(%arg6: index, %arg7: index):
            tensor.yield %cst : f32
          } : tensor<?x?xf32> to tensor<16x?xf32>
          %expanded = tensor.expand_shape %padded [[0, 1], [2, 3]] : tensor<16x?xf32> into tensor<1x16x?x1xf32>
          %transposed = linalg.transpose ins(%expanded : tensor<1x16x?x1xf32>) outs(%extracted_slice_0 : tensor<1x?x16x1xf32>) permutation = [0, 2, 1, 3] 
          %inserted_slice = tensor.insert_slice %transposed into %arg5[%arg2, %arg4, 0, 0] [1, %20, 16, 1] [1, 1, 1, 1] : tensor<1x?x16x1xf32> into tensor<?x?x16x1xf32>
          scf.yield %inserted_slice : tensor<?x?x16x1xf32>
        }
        scf.yield %19 : tensor<?x?x16x1xf32>
      }
      flow.dispatch.tensor.store %18, %7, offsets = [%arg0, %arg1, 0, 0], sizes = [%10, %13, 16, 1], strides = [1, 1, 1, 1] : tensor<?x?x16x1xf32> -> !flow.dispatch.tensor<writeonly:tensor<?x?x16x1xf32>>{%4, %5}
    }
  }
  return
}
```

**Comment by hanhanW** [comment]
This is the fusion example we want to vectorize:

```mlir
func.func @pack_LHS_1089_21_dispatch_0_generic_1089x21_f32() {
  %c1 = arith.constant 1 : index
  %c16 = arith.constant 16 : index
  %c21 = arith.constant 21 : index
  %c69 = arith.constant 69 : index
  %c0 = arith.constant 0 : index
  %cst = arith.constant 3.40282347E+38 : f32
  %cst_0 = arith.constant 0.000000e+00 : f32
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<21xf32>>
  %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<1089x21xf32>>
  %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<69x21x16x1xf32>>
  %workgroup_id_x = hal.interface.workgroup.id[0] : index
  %workgroup_count_x = hal.interface.workgroup.count[0] : index
  %workgroup_id_y = hal.interface.workgroup.id[1] : index
  %workgroup_count_y = hal.interface.workgroup.count[1] : index
  %3 = affine.apply affine_map<()[s0] -> (s0 * 16)>()[%workgroup_id_y]
  %4 = affine.apply affine_map<()[s0] -> (s0 * 16)>()[%workgroup_count_y]
  scf.for %arg0 = %3 to %c69 step %4 {
    %5 = affine.min affine_map<(d0) -> (-d0 + 69, 16)>(%arg0)
    %6 = affine.apply affine_map<()[s0] -> (s0 * 21)>()[%workgroup_id_x]
    %7 = affine.apply affine_map<()[s0] -> (s0 * 21)>()[%workgroup_count_x]
    scf.for %arg1 = %6 to %c21 step %7 {
      %8 = flow.dispatch.tensor.load %2, offsets = [%arg0, %arg1, 0, 0], sizes = [%5, 21, 16, 1], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<writeonly:tensor<69x21x16x1xf32>> -> tensor<?x21x16x1xf32>
      %9 = affine.min affine_map<(d0, d1) -> (d1 * -16 + 1089, d0 * 16)>(%5, %arg0)
      %10 = flow.dispatch.tensor.load %0, offsets = [%arg1], sizes = [21], strides = [1] : !flow.dispatch.tensor<readonly:tensor<21xf32>> -> tensor<21xf32>
      %11 = affine.apply affine_map<(d0) -> (d0 * 16)>(%arg0)
      %12 = flow.dispatch.tensor.load %1, offsets = [%11, %arg1], sizes = [%9, 21], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<1089x21xf32>> -> tensor<?x21xf32>
      %13 = scf.for %arg2 = %c0 to %5 step %c1 iter_args(%arg3 = %8) -> (tensor<?x21x16x1xf32>) {
        %14 = scf.for %arg4 = %c0 to %c21 step %c16 iter_args(%arg5 = %arg3) -> (tensor<?x21x16x1xf32>) {
          %15 = affine.min affine_map<(d0) -> (-d0 + 21, 16)>(%arg4)
          %16 = affine.min affine_map<(d0, d1) -> (16, d0 - d1 * 16)>(%9, %arg2)
          %17 = affine.apply affine_map<(d0) -> (d0 * 16)>(%arg2)
          %extracted_slice = tensor.extract_slice %10[%arg4] [%15] [1] : tensor<21xf32> to tensor<?xf32>
          %extracted_slice_1 = tensor.extract_slice %12[%17, %arg4] [%16, %15] [1, 1] : tensor<?x21xf32> to tensor<?x?xf32>
          %18 = tensor.empty(%16, %15) : tensor<?x?xf32>
          %19 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%extracted_slice, %extracted_slice_1 : tensor<?xf32>, tensor<?x?xf32>) outs(%18 : tensor<?x?xf32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[16, 21], [1, 16], [0, 0]]>} {
          ^bb0(%in: f32, %in_3: f32, %out: f32):
            %21 = arith.addf %in, %in_3 : f32
            %22 = arith.minf %21, %cst : f32
            %23 = arith.maxf %22, %cst_0 : f32
            linalg.yield %23 : f32
          } -> tensor<?x?xf32>
          %extracted_slice_2 = tensor.extract_slice %arg5[%arg2, %arg4, 0, 0] [1, %15, 16, 1] [1, 1, 1, 1] : tensor<?x21x16x1xf32> to tensor<1x?x16x1xf32>
          %20 = affine.apply affine_map<(d0) -> (-d0 + (d0 ceildiv 16) * 16)>(%16)
          %padded = tensor.pad %19 low[0, 0] high[%20, 0] {
          ^bb0(%arg6: index, %arg7: index):
            tensor.yield %cst_0 : f32
          } : tensor<?x?xf32> to tensor<16x?xf32>
          %expanded = tensor.expand_shape %padded [[0, 1], [2, 3]] : tensor<16x?xf32> into tensor<1x16x?x1xf32>
          %transposed = linalg.transpose ins(%expanded : tensor<1x16x?x1xf32>) outs(%extracted_slice_2 : tensor<1x?x16x1xf32>) permutation = [0, 2, 1, 3] 
          %inserted_slice = tensor.insert_slice %transposed into %arg5[%arg2, %arg4, 0, 0] [1, %15, 16, 1] [1, 1, 1, 1] : tensor<1x?x16x1xf32> into tensor<?x21x16x1xf32>
          scf.yield %inserted_slice : tensor<?x21x16x1xf32>
        }
        scf.yield %14 : tensor<?x21x16x1xf32>
      }
      flow.dispatch.tensor.store %13, %2, offsets = [%arg0, %arg1, 0, 0], sizes = [%5, 21, 16, 1], strides = [1, 1, 1, 1] : tensor<?x21x16x1xf32> -> !flow.dispatch.tensor<writeonly:tensor<69x21x16x1xf32>>
    }
  }
  return
}
```

**Comment by hanhanW** [comment]
Another example about fusion (elementwise + pack):

```mlir
func.func @main(%2: tensor<1x8xf32>) -> tensor<1x16x16x1xf32> {
  %cst = arith.constant 3.40282347E+38 : f32
  %cst_0 = arith.constant 0.000000e+00 : f32
  %cst_1 = arith.constant dense<3.14> : tensor<1x8xf32>
  %3 = tensor.empty() : tensor<1x8xf32>
  %4 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%cst_1, %2 : tensor<1x8xf32>, tensor<1x8xf32>) outs(%3 : tensor<1x8xf32>) {
  ^bb0(%in: f32, %in_2: f32, %out: f32):
    %6 = arith.addf %in, %in_2 : f32
    %7 = arith.minf %6, %cst : f32
    %8 = arith.maxf %7, %cst_0 : f32
    linalg.yield %8 : f32
  } -> tensor<1x8xf32>
  %5 = tensor.empty() : tensor<1x16x16x1xf32>
  %pack = tensor.pack %4 padding_value(%cst_0 : f32) inner_dims_pos = [0, 1] inner_tiles = [16, 1] into %5 : tensor<1x8xf32> -> tensor<1x16x16x1xf32>
  return %pack : tensor<1x16x16x1xf32>
}
```

IR before vectorization:

```mlir
func.func @main_dispatch_11_generic_1x8_f32() {
  %c16 = arith.constant 16 : index
  %c200704 = arith.constant 200704 : index
  %c200768 = arith.constant 200768 : index
  %cst = arith.constant 3.40282347E+38 : f32
  %cst_0 = arith.constant 0.000000e+00 : f32
  %cst_1 = arith.constant dense_resource<__elided__> : tensor<1x8xf32>
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c200704) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<1x8xf32>>
  %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c200768) : !flow.dispatch.tensor<writeonly:tensor<1x16x16x1xf32>>
  %workgroup_id_x = hal.interface.workgroup.id[0] : index
  %workgroup_count_x = hal.interface.workgroup.count[0] : index
  %2 = affine.apply affine_map<()[s0] -> (s0 * 8)>()[%workgroup_id_x]
  %3 = affine.apply affine_map<()[s0] -> (s0 * 8)>()[%workgroup_count_x]
  scf.for %arg0 = %2 to %c16 step %3 {
    %4 = flow.dispatch.tensor.load %1, offsets = [0, %arg0, 0, 0], sizes = [1, 8, 16, 1], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<writeonly:tensor<1x16x16x1xf32>> -> tensor<1x8x16x1xf32>
    %5 = affine.apply affine_map<(d0) -> (-d0 + 8)>(%arg0)
    %extracted_slice = tensor.extract_slice %cst_1[0, %arg0] [1, %5] [1, 1] : tensor<1x8xf32> to tensor<1x?xf32>
    %6 = flow.dispatch.tensor.load %0, offsets = [0, %arg0], sizes = [1, %5], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<1x8xf32>> -> tensor<1x?xf32>
    %extracted_slice_2 = tensor.extract_slice %extracted_slice[0, 0] [1, %5] [1, 1] : tensor<1x?xf32> to tensor<1x?xf32>
    %extracted_slice_3 = tensor.extract_slice %6[0, 0] [1, %5] [1, 1] : tensor<1x?xf32> to tensor<1x?xf32>
    %7 = tensor.empty(%5) : tensor<1x?xf32>
    %8 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%extracted_slice_2, %extracted_slice_3 : tensor<1x?xf32>, tensor<1x?xf32>) outs(%7 : tensor<1x?xf32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[0, 8], [1, 16], [0, 0]]>} {
    ^bb0(%in: f32, %in_5: f32, %out: f32):
      %10 = arith.addf %in, %in_5 : f32
      %11 = arith.minf %10, %cst : f32
      %12 = arith.maxf %11, %cst_0 : f32
      linalg.yield %12 : f32
    } -> tensor<1x?xf32>
    %padded = tensor.pad %8 low[0, 0] high[15, %arg0] {
    ^bb0(%arg1: index, %arg2: index):
      tensor.yield %cst_0 : f32
    } : tensor<1x?xf32> to tensor<16x8xf32>
    %expanded = tensor.expand_shape %padded [[0, 1], [2, 3]] : tensor<16x8xf32> into tensor<1x16x8x1xf32>
    %extracted_slice_4 = tensor.extract_slice %expanded[0, 0, 0, 0] [1, 16, 8, 1] [1, 1, 1, 1] : tensor<1x16x8x1xf32> to tensor<1x16x8xf32>
    %9 = tensor.empty() : tensor<1x8x16xf32>
    %transposed = linalg.transpose ins(%extracted_slice_4 : tensor<1x16x8xf32>) outs(%9 : tensor<1x8x16xf32>) permutation = [0, 2, 1] 
    %inserted_slice = tensor.insert_slice %transposed into %4[0, 0, 0, 0] [1, 8, 16, 1] [1, 1, 1, 1] : tensor<1x8x16xf32> into tensor<1x8x16x1xf32>
    flow.dispatch.tensor.store %inserted_slice, %1, offsets = [0, %arg0, 0, 0], sizes = [1, 8, 16, 1], strides = [1, 1, 1, 1] : tensor<1x8x16x1xf32> -> !flow.dispatch.tensor<writeonly:tensor<1x16x16x1xf32>>
  }
  return
}
```

**Comment by hanhanW** [comment]
All the items are done, closing the issue.
