### ISSUE TITLE
[Epic] SPMD perf optimizations

### ISSUE THREAD

**Issue by okkwon** [iree-org/iree#13762]
```[tasklist]
### Tasks
- [ ] https://github.com/openxla/iree/issues/13763
- [ ] https://github.com/openxla/iree/issues/13764
- [ ] https://github.com/openxla/iree/issues/13794
```
