### ISSUE TITLE
Add initial support for GPU ukernels.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#14028]
To support work like #13960 we should plumb through ukernel.generic as we have on the CPU side. To start the ukernels could be entire workgroups worth of work and so long as they bufferize correctly and get converted to calls things _should_ work. We can work on ergonomics in subsequent work (same things we need on CPU side in #12300).

```[tasklist]
### Tasks
- [ ] Ensure GPU codegen bypasses tile/distribute when there's no workgroup_count_from_dag_root_op
- [ ] mkdir and setup a builtins bitcode library for CUDA kernels ala what the custom_dispatch/cuda/kernels/ sample does
- [ ] Link the builtins alongside CUDA's libdevice when needed
- [ ] Add custom_dispatch/cuda/functions/ sample demonstrating ukernel functions and external bitcode
```

Goal would be to have #13960 be able to insert ops like this:
```mlir
%partial = flow.dispatch.region[%dims...] -> (tensor<...>, ...) {
  // https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94#file-topk_reduction-cu-L153-L197
  %0 = iree_codegen.ukernel.generic "topk_partial" ...
  flow.return %0 ...
} count(%dims...) {
  // https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94#file-topk_reduction-cu-L254-L258
  %gridx = arith.divui %dims ....
  flow.return %gridx, %gridy, %gridz
}
%final = flow.dispatch.region[%dims...] -> (tensor<...>, ...) {
  // https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94#file-topk_reduction-cu-L200-L242
  %1 = iree_codegen.ukernel.generic "topk_final" ...
  flow.return %1 ...
} count(%dims...) {
  // https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94#file-topk_reduction-cu-L260-L263
  %gridx = arith.divui %dims ....
  flow.return %gridx, %gridy, %gridz
}
```

And then have those generic ops turn into calls in a .cu file compiled to .bc and linked in.
The flow/input-level pass inserting the ops can use the functionality in #14009 by having the CUDATarget add a "codegen.prefers_split_topk_or_whatever" attribute to the configuration dictionary and checking for that with `IREE::HAL::DeviceTargetAttr::lookupConfigAttrAll(op, "codegen.prefers_split_topk_or_whatever")` to switch itself on.

**Comment by benvanik** [comment]
Some things from https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94 to specifically figure out:
* [ ] parameterization in codegen for things like TB_PARTIAL - could just be what's on the device config dictionary as an IntegerAttr
* [ ] any additional device info we need to preserve from outside? or can all be done using nv reflection?

**Comment by grypp** [comment]
I have a question regarding the provided code snippet. I noticed that the code calls the `topk_partial` as a device function within the CUDA kernel generated by IREE. If I misunderstand this part, please disregard my message.

```
%partial = flow.dispatch.region[%dims...] -> (tensor<...>, ...) {
  // https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94#file-topk_reduction-cu-L153-L197
  %0 = iree_codegen.ukernel.generic "topk_partial" ...
  flow.return %0 ...
} count(%dims...) {
  // https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94#file-topk_reduction-cu-L254-L258
  %gridx = arith.divui %dims ....
  flow.return %gridx, %gridy, %gridz
}
```

While the current approach of transforming `ukernel.generic` to a function call through the `LowerUKernelOpsToCallsPass` works, it may not be ideal for our needs. We really need to call a CUDA kernel rather than a device function.

Compiling a device function introduces restrictions on optimizations and limits the utilization of features like `__launch_bounds__`. Additionally, although the device function will eventually be inlined, it may inline inefficient code, resulting in suboptimal performance. On the other hand, calling a CUDA kernel offers several advantages, including the ability to utilize nvcc when necessary.

Can we extend the `flow.dispatch.region` with a `kernel_bind` and nobody? I could propose something like below? We could create another op as well. 

```
%partial = flow.dispatch.region[%dims...] -> (tensor<...>, ...) kernel_bind("topk_partial") {
} count(%dims...) {
  %gridx = arith.divui %dims ....
  flow.return %gridx, %gridy, %gridz
}
```

To implement this modification, we would ensure that a kernel with the name `topk_partial` exists. It's worth noting that name mangling can be avoided by using CUDA-C kernels.

Please let me know your thoughts and whether we can consider implementing this modification.

**Comment by grypp** [comment]
Another question - can we introduce a special dispatch region that actually calls a host function (serves as an intermediary), that calls the CUDA kernel? 

For `sort`, I used `cub` header library and it has a host function (https://gist.github.com/grypp/4f9b115e197de26877cce2bb08a89ecf#file-topk_and_sort-cu-L314-L329). It is also beneficial for `cutlass`.

If it is not possible, I can probably implement a cuda kernel for `sort`.

**Comment by benvanik** [comment]
A few questions in here; will try to answer what I think the root ones may be but am happy to go into more detail or chat about other stuff if this doesn't actually answer your questions :) There's also a bit of pragmatism vs. long-term here where what's ideal may take a few steps but if we make the right pragmatic solutions now it'll let us get there a lot faster with a lot less work.

Embedded device code is all you get for the core portable IREE build as host code requires runtime deployment changes and is only done for exceptional cases - think of it like adding syscalls to the linux kernel: you can make a million changes in user level for every one change to the kernel level API. That doesn't mean new syscalls can't go in but that they change with a very different cadence and with a much higher bar for generalizability. Calling CUDA user libraries doesn't really meet that and that's why the openxla-nvgpu plugin exists as a dumping ground for such things ("this is just nvidia specific stuff for people willing to deal with all the deployment/versioning/compatibility/targeting issues"). Another equivalence would be what gets added to clang/the C++ language (builtins, attributes, libc/STL, etc) vs. what a user may author and compile with clang (any random C++ code): std::sort is provided by the STL and available everywhere _and_ users are welcome to compile code using cub _but_ std::sort will never call cub as its internal implementation. Custom modules in IREE - like externally linked compilation units in normal programs - are possible for users and we do have streamable calls that allow for scheduling device work on CUDA streams/graphs but as they'd be calling CUDA libraries/runtime CUDA code those belong in the external plugins for the same reason we don't expose CUDA user libraries in the HAL.

There's still a lot that can be done with device code, though, and the only restriction is around what is launched. Though even that's not entirely restrictive - dynamic parallelism, for example, can be used to do certain types of device-side launches (good particularly for things like sorts/reductions/etc as they can even support data-dependent dynamic shapes and fit well with the limitations of dynamic parallelism). It's even possible to launch graphs now from device meaning that we could have device-side compiled programs that constructed graphs on startup and then launched them from the dispatches we create in the compiler (with a bit of goo). From the compiler you can emit any host code you want so long as it's supported by the host lowerings - so arbitrary arithmetic for workgroup count calculations, or passing in values computed on the host as additional dispatch operands, or adding global transient buffers by attaching new tied `flow.tensor.alloc` operand (though new global allocations is always a red flag), etc.

The key thing to think about is that what is inside a dispatch region is largely opaque from the perspective of the host-side IREE code and what a ukernel is can vary. There's nothing saying a ukernel is a function, though if it is that makes things way easier. A ukernel could be handled by a pass that expands it to other dialects/ops, or inlines asm blobs, or whatever. Passes processing the ukernel ops can also do whatever they want like setting attributes on the parent function for launch bounds: `there's a iree_codegen.ukernel.generic "topk_final" so add the codegen.cuda.launch_bounds attribute to the parent func.func and have the LLVM dialect conversion convert the attributes` - afterall, `__launch_bounds__` is just some metadata. There's not much worry about inlining as when the entire dispatch is a single function call there's nothing to prevent inlining and nothing that not performing inlining could really hurt - and you control the bitcode so you can throw the always_inline attribute on your function. Not much is very sensitive to single uniform tail call branches nowadays, anyway :)

nvcc is possible even with device-side code but it's not something we want to rely on in the core compiler: it's akin to gcc shelling out to clang to compile a particular function because it does slightly better in one case for one random pass at hoisting one variable - for a particular version of the compiler with a particular arch. A user should have the option of mashing the two compilers together (and we demonstrate this with the `custom_dispatch/cuda/kernels/` sample that uses nvcc) but the core compiler doing it is weird. As a low-level toolchain our goal is to be as easy for users to smash together with other toolchains as possible and the way we ensure that is by keeping what we do focused and predictable.

So yeah, the best thing will always be to generate things in the compiler whether that's through linalg->vector->etc or ukernel->custom/llvm/inline asm/etc as that keeps us retargetable, simplifies the build for users, keeps deployment hermetic, and has the highest durability. The fallback for that is the externally-defined bitcode compiled with clang from .cu files that gets linked in to handle ukernels as that's a fairly automatic path with low maintenance burden (same as CPU and other targets). One step more complex is the same externally-defined bitcode but injected without ukernels as it's not much more work beyond setting up the functions/configuration in a pass vs letting the ukernel mechanism handle that. Beyond that it gets into user-land concerns as the tradeoffs go from how we as compiler authors do something internally to material impacts on users of the compiler in what they can target when and with what reliability.

**Comment by MaheshRavishankar** [comment]
Ben provided more context above, I am going to answer some specific questions.

> I have a question regarding the provided code snippet. I noticed that the code calls the `topk_partial` as a device function within the CUDA kernel generated by IREE. If I misunderstand this part, please disregard my message.
> 
> ```
> %partial = flow.dispatch.region[%dims...] -> (tensor<...>, ...) {
>   // https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94#file-topk_reduction-cu-L153-L197
>   %0 = iree_codegen.ukernel.generic "topk_partial" ...
>   flow.return %0 ...
> } count(%dims...) {
>   // https://gist.github.com/grypp/859d40304326119a71a2cc9db0b5fc94#file-topk_reduction-cu-L254-L258
>   %gridx = arith.divui %dims ....
>   flow.return %gridx, %gridy, %gridz
> }
> ```
> 
> While the current approach of transforming `ukernel.generic` to a function call through the `LowerUKernelOpsToCallsPass` works, it may not be ideal for our needs. We really need to call a CUDA kernel rather than a device function.
> 
> Compiling a device function introduces restrictions on optimizations and limits the utilization of features like `__launch_bounds__`. Additionally, although the device function will eventually be inlined, it may inline inefficient code, resulting in suboptimal performance. On the other hand, calling a CUDA kernel offers several advantages, including the ability to utilize nvcc when necessary.
> 

I dont think that will be the case. We are inlining at LLVM level (not at PTX level where inlining might not be efficient). We are essentially inlining and compiling the inlined code with full optimization. I dont expect that to be inefficient. 

> Can we extend the `flow.dispatch.region` with a `kernel_bind` and nobody? I could propose something like below? We could create another op as well.
> 
> ```
> %partial = flow.dispatch.region[%dims...] -> (tensor<...>, ...) kernel_bind("topk_partial") {
> } count(%dims...) {
>   %gridx = arith.divui %dims ....
>   flow.return %gridx, %gridy, %gridz
> }
> ```
> 
> To implement this modification, we would ensure that a kernel with the name `topk_partial` exists. It's worth noting that name mangling can be avoided by using CUDA-C kernels.

That is possible but cannot be done in tree. I think there is a different mechanism to do that in the plugin.

> 
> Please let me know your thoughts and whether we can consider implementing this modification.

**Comment by MaheshRavishankar** [comment]
> Another question - can we introduce a special dispatch region that actually calls a host function (serves as an intermediary), that calls the CUDA kernel?
> 
> For `sort`, I used `cub` header library and it has a host function ([gist.github.com/grypp/4f9b115e197de26877cce2bb08a89ecf#file-topk_and_sort-cu-L314-L329](https://gist.github.com/grypp/4f9b115e197de26877cce2bb08a89ecf#file-topk_and_sort-cu-L314-L329)). It is also beneficial for `cutlass`.

I think cub also has device functions you could use... but my sense if we are going to use cub/cutlass etc. we might as well just compile to a full CUDA kernel and use that from the nvgpu plugin.

> 
> If it is not possible, I can probably implement a cuda kernel for `sort`.

**Comment by ezhulenev** [comment]
> Can we extend the flow.dispatch.region with a kernel_bind and nobody? I could propose something like below?

Isn't it pretty much `hal.executable.source` (see example here https://github.com/openxla/iree/blob/main/samples/custom_dispatch/cuda/kernels/example.mlir#L44)?

What you can do today is to pattern match `stablehlo.topk` and rewrite it into `hal.executable.source` + `flow.dispatch`, the tricky part is how to get PTX/CUBIN from a C++ source at compile time, you can do it with some CMake/bazel "magic" or be adventurous and call libnvrtc (https://docs.nvidia.com/cuda/nvrtc/index.html#basic-usage)

> Another question - can we introduce a special dispatch region that actually calls a host function (serves as an intermediary), that calls the CUDA kernel?

You can register a custom module with custom calls or streamable calls. Can't find example for streamable calls, but cudnn.execute is somewhat relevant: https://github.com/openxla/openxla-nvgpu/blob/main/runtime/src/openxla/runtime/nvgpu/cudnn/cudnn_module.cpp#L296-L304 - it's just a `func.call @cudnn.execute` in the IR, and it launches cuDNN graph (which is just a CUDA kernel really) on a stream

This would be something like this:
1. Register `XlaExtModule : public vm::NativeModule`
2. Export `xla.ext.topk` custom call
3. Rewrite `stablehlo.topk` into `xla.ext.topk` custom all (streamable call)
4. Device kernels will be compiled as a part of custom module compilation

**Comment by grypp** [comment]
clang frontend uses a pipeline when it compiles a device function and this pipeline is different as it takes the CUDA kernel for it (similar story for nvcc).

Let me first compare this proposal vs mine

**This proposal**
```
[clang] 	Compiles a device function and keeps it in cuda_device_function.bc
[iree-compiler] Generates a CUDA kernel thats calls the device function in cuda_device_function.bc
[iree runtime]  Calls iree CUDA kernel
```

**My proposal:**
```
[clang] 	Compiles a CUDA kernel and keeps it in cuda_kernel.bc
[iree-compiler] ---
[iree runtime]  Calls iree CUDA kernel in cuda_kernel.bc
```

Problems in this issue:
1) LLVM in cuda_device_function.bc might not be well optimized. 
2) iree-compiler generates a kernel that causes indirection. The kernel only calls a function in cuda_device_function.bc. Then why do we need iree to generate a kernel?

Advantages of my proposal:
1) LLVM in cuda_kernel.bc is the well optimized LLVM by clang.
2) Removes indirection

My proposal and this proposal sometimes might yield the similar PTX, but it is hard to guarantee. 

**Concrete example**

clang does not generate LLVM's `alwaysinline ` attribute for a device function that does not have `__force_inline__` in CUDA. However, clang also removes a function with `__force_inline__` if there is caller. This is one example exactly the case that will happen if we follow this proposal.

I had to add `alwaysinlined` manually when I was implementing cutlass microkernel work.
https://github.com/grypp/iree/blob/microkernel/compiler/src/iree/compiler/Codegen/Microkernels/CUDA/Precompiled/build.sh#L27-L49

I don't think we want to use things like dynamic parallelism. Calling a kernel from device has larger overheads from host. More details in my [PhD thesis](https://upcommons.upc.edu/bitstream/handle/2117/125844/TGO1de1.pdf?sequence=1&isAllowed=y).

**Comment by grypp** [comment]
I must say that this proposal offers many other advantages. I am definitely not saying let's not do that. For example, my cutlass microkernel #12026 could use this perfectly. 

I want to avoid hitting a performance bug just because clang isn't generating something for the device function.

We can implement this proposal to get the ball rolling, and I connect `topk` to `sort`. We can then implement my proposal in the nvgpu plugin later. Does it sounds makes sense?

**Comment by MaheshRavishankar** [comment]
@grypp whether you use this or not, I am plumbing it through anyway... its upto someone else to decide what exact steps you want to take.

> clang does not generate LLVM's `alwaysinline ` attribute for a device function that does not have `__force_inline__` in CUDA. However, clang also removes a function with `__force_inline__` if there is caller. This is one example exactly the case that will happen if we follow this proposal.

https://github.com/openxla/iree/blob/bd80c9aa59ac78ad3126c467a26f44f5a6e7f90d/compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp#L473 is where you always inline... I think you are indexing on surface level issues... Internally CUDA compiler is an LLVM compiler. So there is no magic in anything the CUDA compiler does (apart from some magic on scheduling that is orthogonal). The issue with your microkernel path was you were trying to inline at PTX level which is not the intended use of PTXAS (inlining using LLVM is bread-and-butter for it). I cant buy the optimization argument. The CPU ukernel library is way more involved than anything you are proposing here and everything inlines/dces/optimizes (actually over-optimizes). Having said that, I am more interested in getting this path litup on CUDA side. If you want to use it or not, thats upto you.

**Comment by benvanik** [comment]
We'll not be shipping CUDA bitcode/PTX with the runtime and doing it with the compiler allows for many more options, anyway. We've got this all pretty well developed on the CPU side already, for example, where we support both our own bitcode linking as well as an external system linker and one could do the same on the CUDA side by allowing for an external linker if it really helped. We could allow .bc, .o, .a, .ptx, whatever and fleshing that out has been on the TODO list for ages. But for core components of the platform there are extremely strong downsides to using another toolchain - even if it leaves 10% performance on the table the goal is not to achieve peak at all costs but to build something sustainable and scalable and then allow users to sprinkle in what they need. As with the std::sort example it's not that std::sort is perfect but having an std::sort implementation in the compiler does not prevent anyone from bringing their own more suited to their usage - the key feature of std::sort is that it is always available and performs reasonably well - sort and topk in ML are like that :)

**Comment by grypp** [comment]
Thank you to everyone who is taking the time to implement this path. I think it will be a useful one; absolutely necessary for microkernels. 

Let the performance decide which way we will choose for `topk` and `sort`.

FWIW, I used bitcode linking for my cutlass microkernels. I compiled the cutlass code as a device function by clang and linked as below. The microkernels were not inlined, that's why I had to manually add `alwaysinline` the LLVM IR.
https://github.com/grypp/iree/blob/9cbdfab70c99c038e7914d347342938a18dd2a49/compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp#L285

**Comment by MaheshRavishankar** [comment]
> Thank you to everyone who is taking the time to implement this path. I think it will be a useful one; absolutely necessary for microkernels.
> 
> Let the performance decide which way we will choose for `topk` and `sort`.
> 
> FWIW, I used bitcode linking for my cutlass microkernels. I compiled the cutlass code as a device function by clang and linked as below. The microkernels were not inlined, that's why I had to manually add `alwaysinline` the LLVM IR. [grypp/iree@`9cbdfab`/compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp#L285](https://github.com/grypp/iree/blob/9cbdfab70c99c038e7914d347342938a18dd2a49/compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp#L285)

The snippet I pointed to does exactly that. It marks all the linked functions `alwaysinline`.

**Comment by qcolombet** [comment]
I haven't looked at any of this, but I feel that @grypp's proposal offer the right level of abstraction to connect any sort of library provider like cuBLAS, cuDNN.
Now, if I understand correctly what @ezhulenev was saying, this pretty much already exists. If anything we may need an easier way to describe how we get there.

For instance, what's required here seems like an extension of what @benvanik's already implemented in https://github.com/openxla/iree/pull/12240.

**Comment by benvanik** [comment]
This all already exists, and what this thread has been talking about :)

**Comment by MaheshRavishankar** [comment]
I think we might have some wires crossed. Ill try to summarize the options we have (and folks can correct me if I am wrong, which I am pretty sure I am.)

1) We implement topk (and potentially sort) as a full kernel. I think the constraint here is that we cant have the CUDA/PTX for topk/sort shipped with the runtime by default... we can embed the PTX into generated `.vmfb` (afaiu). 
   1 a) . We have the PTX/CUDA code for topk/sort somewhere in tree. When needed instead of generating the code for topk/sort we just use the PTX for this (compiled using clang or something during `iree-compile` build time).
   1 b). If 1(a) is not possible, have the kernels/implementation in the plugin. This would require even the transformation to get to these two kernels (the split-k) into the plugin.
2) We can use the ukernel approach, but that does not seem very different from 1-a above.

Everything here is already there to use... just need to pick a path.

**Comment by grypp** [comment]
> We implement topk (and potentially sort) as a full kernel. I think the constraint here is that we cant have the CUDA/PTX for topk/sort shipped with the runtime by default... we can embed the PTX into generated .vmfb (afaiu).

clang gave good performance for `topk` 😱 We could actually link bitcode for `topk`. But I agree that PTX is safer option in long term. I had a lot of trouble with clang with cutlass, for example. 

> 1 a) . We have the PTX/CUDA code for topk/sort somewhere in tree. 

PTX is target dependent therefore we will need to pre-compile many kernels. For example, I've 2 kernels for `topk` and 1 for `sort`. We need them for multiple data types and some template parameters such as CTA_SIZE. Plus, we need to generate PTX per SM architecture. 

If I need to rough calculation:
```
3 kernels * 4 data types * 2 CTA_SIZE = 24 kernels per SM. 
24 * 3 sm architecture (`sm_80, sm_90` for datacenter, and `sm_86` for my destop :) ) = 72 kernels?
```
Is having many kernels acceptable in tree?

> When needed instead of generating the code for topk/sort we just use the PTX for this (compiled using clang or something during iree-compile build time).

I need to generate multiple dispatch region. Can we do this in `flow` level? Is it allowed? 

> 1 b). If 1(a) is not possible, have the kernels/implementation in the plugin. This would require even the transformation to get to these two kernels (the split-k) into the plugin.

Can we implement everything (generating dispatch region, linking ptx) in the plugin without touching iree? 
If yes, this is the way :)

**Comment by MaheshRavishankar** [comment]
> > We implement topk (and potentially sort) as a full kernel. I think the constraint here is that we cant have the CUDA/PTX for topk/sort shipped with the runtime by default... we can embed the PTX into generated .vmfb (afaiu).
> 
> clang gave good performance for `topk` 😱 We could actually link bitcode for `topk`. But I agree that PTX is safer option in long term. I had a lot of trouble with clang with cutlass, for example.
> 
> > 1 a) . We have the PTX/CUDA code for topk/sort somewhere in tree.
> 
> PTX is target dependent therefore we will need to pre-compile many kernels. For example, I've 2 kernels for `topk` and 1 for `sort`. We need them for multiple data types and some template parameters such as CTA_SIZE. Plus, we need to generate PTX per SM architecture.
> 
> If I need to rough calculation:
> 
> ```
> 3 kernels * 4 data types * 2 CTA_SIZE = 24 kernels per SM. 
> 24 * 3 sm architecture (`sm_80, sm_90` for datacenter, and `sm_86` for my destop :) ) = 72 kernels?
> ```

I'd say thats the problem with the PTX approach. My suggestion here for in-tree is to not ship PTX, but "ship" the `.bc` file. Can that be done without specializing for each SM? If you want to ship all that PTX, that will probably have to live in the plugin cause its a cost that should be added only on need basis.

> 
> Is having many kernels acceptable in tree?
> 
> > When needed instead of generating the code for topk/sort we just use the PTX for this (compiled using clang or something during iree-compile build time).
> 
> I need to generate multiple dispatch region. Can we do this in `flow` level? Is it allowed?

You can generate multiple dispatch regions just before what is the Flow pipeline today. So do that as the step before what is today `iree-compile`. You can create `flow.dispatch.region`s you need and pass it to IREE. Rest of Flow should not touch it (if it does, its a bug and we fix it).

> 
> > 1 b). If 1(a) is not possible, have the kernels/implementation in the plugin. This would require even the transformation to get to these two kernels (the split-k) into the plugin.
> 
> Can we implement everything (generating dispatch region, linking ptx) in the plugin without touching iree? If yes, this is the way :)

Yes, potentially. if I can plumb the micro-kernel support through `iree_codegen.ukernel.generic` through, then we shouldnt need to touch IREE.

**Comment by benvanik** [comment]
Yeah, if you did a .cu, compiled it with clang to bitcode, and then used compiler reflection/injection of parameters you only need a single .cu and a single .bc - that's why we built all of this - the combinatorial explosion of PTX is precisely what we don't want/can't have.
