### ISSUE TITLE
Optimize constant upload on all targets.

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#14607]
Tracking the work to get zero-copy constant uploading on all targets. This requires changing how the compiler emits large constant uploads to use a new queue-ordered streaming API such that we can take advantage of platform-level streaming mechanisms without needing to stage all of the memory. Improving the import path on backends that support it will help integrated accelerators that can directly access host memory (Metal, Vulkan) while the file streaming will help dedicated accelerators (CUDA, Vulkan, etc).

```[tasklist]
### Phase 0
- [x] Add `iree_hal_file_t`/`hal.file` API with experimental memory wrapping.
- [x] Add emulated memory file and streaming copy support.
- [x] Rework constant upload to use import + file streaming.
- [x] Ensure zero-copy Vulkan buffer imports on integrated GPUs.
```

```[tasklist]
### Phase 1
- [ ] Figure out how to remove `hal.ex.file.from_memory`.
- [ ] #14605
- [ ] Replace some tooling usage of synchronous host<->device transfers with file operations.
```

```[tasklist]
### Specializations
- [ ] Add cuFile support for CUDA file streaming.
- [ ] Add MTLIOCommandQueue support for Metal file streaming.
- [ ] https://github.com/openxla/iree/issues/14608
- [ ] Add overlapped IO support for Windows CPU file streaming.
- [ ] Investigate Mac/Linux options (kqueue/epoll/io_uring/etc) for CPU file streaming.
```
