### ISSUE TITLE
Upgrade CPU benchmark VMs to c2-standard-60

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#14661]
Currently c2-standard-16 Intel CascadeLake VMs we are using for CPU benchmarking might share the same hardware with other VMs, which can introduce noise. The goal of this task is to:

1. Test c2-standard-60 (with hyper-threading disabled) in postsubmit to see if it provides better stability as the VM has exclusive access to the hardware.
2. Migrate the current CPU benchmarks to run on c2-standatd-60.
  a. We need to decide if porting the existing data to the new benchmark series or not (`c2-standard-16` and `c2-standard-60` technically run on the same hardware, but we still see performance differences even limited and pinned the CPU threads in the tests)

The benefits will be:

- Get more stable benchmark numbers on CPU benchmarks.
- Provide more cores (30 cores, 15 cores per NUMA) for benchmarks with more threads.

[The early test data](https://docs.google.com/spreadsheets/d/1cAlH1-xpA5yXckDpUractrCcfTv6bFmal_CJya0Qo94/edit?resourcekey=0-zwk1XgiRi6OoG07j8zJFrA#gid=11723391) (ran every hours, ~200 runs in April 2023) showed that `c2-standard-60` could give out more stable numbers than `c2-standard-16` on the same benchmarks (results are more concentrated on the sampled means). The experiments was done with hyper-threading enabled on `c2-standard-60`, but we expected to see no worse numbers with hyper-threading disabled.

```[tasklist]
### Tasks
- [x] Add template and create testing VMs
- [x] Run benchmarks on `c2-standard-60` in postsubmit and collect data for at least 1 week
- [x] Decide if we want to do the migration with test results
- [x] Migrate the CPU benchmarks to `c2-standard-60`
- [x] Cleanup and remove `c2-standard-16` runners
```

**Comment by pzread** [comment]
After running the benchmarks on c2-standard-60 in postsubmit for ~2 weeks. Here is the result:

We collected x86_64 benchmark results from 116 commits in the past 2 weeks. For each benchmark, on each commit it reports one data point "the mean run time of 10 repetition runs (`--benchmark_repetitions=10`)". These data points form a benchmark series. Then I use the steps below to normalize the series in order to aggregate all benchmarks:

1. Find the segments in the series such that each segment was using the same benchmark tool and VMFB module (so we expect the run times are the same in a segment)
2. Get the sample mean of each segment. This is to better approximate the actual run time in a segment by suppressing the noise
3. Normalize the data points in each segment with `(data point - segment sample mean) / segment sample mean` 

The normalized series should help us understand how many percents each data point deviates from the approximated actual run time.

In the figure below, we join the normalized series from all 50 benchmarks and plot with different colors for c2-standard-16 and c2-standard-60. In both 1 and 8 threads c2-standard-60 produces more convergent data points comparing to c2-standard-16, with most of the points in the range of +-5%.

If we count the percentage of data points exceeding +-5%, c2-standard-60 shows 0.2% over 5750 data points while c2-standard-16 shows 7%. 

![mean-compare](https://github.com/openxla/iree/assets/2104162/0b7fe50c-8553-42fa-8374-4751a0c5e840)

Static HTML figure: https://storage.googleapis.com/iree-jerry-test/16-60-mean-compare.html

As a result, by switching to c2-standatd-60 we can expect more stable x86_64 benchmark results. Some other improvements such as pinning CPU cores and NUMA nodes could further improve the stability.

**Comment by mariecwhite** [comment]
Nice work!
