### ISSUE TITLE
Add "Developers" section to website

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#15116]
Enough people are asking for this ([recent Discord discussion here](https://discord.com/channels/689900678990135345/692052262494797835/1159515996613263462)) that it makes sense to add a new section for project contributors and integrators. This will broaden the scope of the website from primarily serving an ambiguous group of "users" (hoping to take a model authored in an ML framework and deploy it to some target).

```[tasklist]
### Tasks
- [x] Audit https://github.com/openxla/iree/tree/main/docs/developers and delete/refresh stale pages
- [x] Create docs/website/developers category, index page, etc. and add to website nav
- [x] Determine if the entire docs/developers directory should move into docs/website/developers or only a subset
- [x] Set policy for pages (how standardized / proofread should they be?)
- [x] Move docs across to the new directory
- [x] Run markdownlint on all files added to the website
- [x] Refresh markdown style (icons, headings, callouts, relative links, etc.) for any new website files
```

I could see the "Building from source" section moving under "Developers"... will have to think on that some more.

**Comment by ScottTodd** [comment]
Made some good progress on this today, may have something ready for review soon: 
![image](https://github.com/openxla/iree/assets/4010439/5e7c1cd7-b0fb-417b-8dfe-12c030f6c462)

Still left to write / migrate:

* index page (establishing what is different about the "developers" section)
* benchmarking/profiling
  * we have 7 pages that I'd like to merge into 2-4 somehow
  * see also https://github.com/openxla/iree/issues/14470
* design_docs
  * nearly all are outdated, and I have a pending PR to delete some: https://github.com/openxla/iree/pull/15135
* design_roadmap
  * outdated, also pruned a bit in https://github.com/openxla/iree/pull/15135

The mkdocs markdown style is different in a few ways that make viewing on GitHub directly less useful. TBD how much that matters (would really like for more maintainers and community members to feel empowered and encouraged to contribute to the docs)

**Comment by ScottTodd** [comment]
The "contributing" page is also due for a refresh:

- [ ] instructions on getting collaborator + write access
- [ ] how to navigate CI jobs (lint/formatting, builds, tests, benchmarks)
- [ ] how to find tasks to work on
- [ ] getting productive with development workflows (VSCode, ctest, cross-repo work, etc.)
- [ ] communication styles / norms
