### ISSUE TITLE
Rebase IREE+PyTorch docs onto Turbine

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#15114]
This page is due for an update: https://www.iree.dev/guides/ml-frameworks/pytorch/ ([source here](https://github.com/openxla/iree/blob/main/docs/website/docs/guides/ml-frameworks/pytorch.md))

* Prompted by [this Discord discussion](https://discord.com/channels/689900678990135345/908461811026767952/1156023323566817362)
* Notes and experiments in [this Colab notebook](https://colab.research.google.com/drive/1wZOUdfuMyXJyUiUQe0ivJrcaNvYXZ5hd?usp=sharing)

The current docs gloss over many Python details and start from [torch-mlir](https://github.com/llvm/torch-mlir), while the new project "[SHARK-Turbine](https://github.com/nod-ai/SHARK-Turbine)"
> provides a unified build of IREE, torch-mlir, and auxilliary support for providing a tight integration with PyTorch and other related frameworks.

Some parts of Turbine will likely flow into torch-mlir and IREE, but the general API connection points and workflows are trending in a direction that we'd like to point users down. Specifically, Turbine includes native Dynamo support, integration of the compiler and runtime within eager flows, and good support for features such as dynamic shapes.

```[tasklist]
### Tasks
- [x] Show how to install IREE+PyTorch+Turbine (for now, this will likely change over time)
- [x] Discuss JIT/eager and AOT/export use cases
- [x] Show how to use both JIT and AOT modes
- [x] Include notices about current status (we welcome feedback to improve the developing APIs, etc. etc.)
- [ ] Explain how to debug issues / file useful bug reports? (or link out to other pages)
- [x] Link to sample notebooks, projects, tests, etc. (https://github.com/openxla/iree/issues/15117)
```

**Comment by ScottTodd** [comment]
This sample code would be nice to bring forward into the new Turbine/torch-mlir world: https://github.com/iree-org/iree-torch/tree/main/examples/native_training. It follows a pretty similar model to https://github.com/openxla/iree/tree/main/samples/variables_and_state and https://github.com/openxla/iree/tree/main/samples/dynamic_shapes, which I've been wanting to port to PyTorch (and ideally also JAX).

Samples like those help connect "export out of Python" all the way to "run on mobile/web/embedded/etc." by showing the workflows, C/C++/rust/JS/etc. code, and build configuration needed.
