### ISSUE TITLE
[Epic] Support for target and strategy multi-versioning

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#15334]
# Problem Summary

Currently, The only well-worn path for the compiler today requires the user to specify precisely the target device they are compiling for, and each dispatch will be compiled to a single fixed strategy. This is impractical for real-world deployment of compiled artifacts and is a major reason why downstream projects (https://github.com/nod-ai/SHARK) choose to just invoke the compiler on the client machine, rather than downloading a pre-compiled artifact. This is especially problematic for the kinds of workloads IREE is tailored for: large machine learning models where artifact size is dominated by the weights. Needing to compile two artifacts for a CPU and GPU doubles the amount of storage required by the user, as well as overall compile times. While dependent on the model, thanks to the shared dispatch generation code between targets, IREE should be able to compile + deploy a single artifact for multiple targets and allow users to switch seamlessly between them.

# Goal

The high level goal with this effort is to improve multi-targeting support on two fronts. First, target multi-versioning, allowing the user to specify a range of environments they care about and IREE will compile efficient device code for all such targets, alongside the necessary host code to switch between targets. Second, within a dispatch, compile potentially multiple versions/strategies for the same dispatch and swap between them based on specialization constants and dynamic problem sizes. These two tasks are somewhat orthogonal in terms of which parts of the compiler they concern, but I see the initial steps as sharing the same required cleanups.

# Sample Task List

This is intended to be a list of required tasks. Items below are approximations of what needs to be done and can be updated/adjusted as needed.

```[tasklist]
### General
- [ ] #50
- [ ] #15295
- [ ] #15284
- [ ] #15286
- [ ] #15309
- [ ] https://github.com/openxla/iree/pull/15362
- [ ] Allow specifying a list of the explicit `hal.device.targets` explicitly, similar to the way `vk.target_env` can be specified as a command line argument.
- [ ] Allow `hal.dispatch.extern` to specify the minimum set of required features for an object rather than the exact target environment.
- [ ] https://github.com/openxla/iree/issues/15336
```

```[tasklist]
### General Codegen
- [ ] #15321
- [ ] Create `MaterializeExecutableVariantsPass` as a precursor to `TranslateExecutablesPass` that expands/contracts variants based on selected lowering strategies. This avoids excessive duplication of codegen work when the number of similar variants to compile for explodes.
- [ ] Nest the majority of the strategy specific code generation on functions. This allows setting translation info on the function rather than the export as a precursor to specialization and horizontal fusion.
- [ ] Allow multiple strategies per entry point and private function.
- [ ] Add an interface to `DispatchLoweringPipeline` strategies that specifies high level required, unneeded, and unknown capabilities/extensions/features to inform `MaterializeExecutableVariantsPass` how to create new variants.
```

```[tasklist]
### SPIR-V
- [ ] #15383
- [ ] Allow specifying trinary (present, not present, unknown) state on capabilities and extensions. This could be achieved by using the `vk.target_env` as the target attribute and only do the conversion to the `spirv.target_env` when materializing the variant.
- [ ] Compile multiple SPIR-V modules per variant and implement a linking stage that connects functions with more relaxed feature requirements with stricter modules.
- [ ] Add support for specialization constants.
```

```[tasklist]
### CPU
- [ ] Tie in materialization of data tiling encodings?
```

cc @benvanik @MaheshRavishankar @antiagainst @kuhar

**Comment by qedawkins** [comment]
This is a pseudo-clone of #50 :D
