### ISSUE TITLE
Fold transpose into pack/unpack ops

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15367]
tensor.pack and tensor.unpack ops have transpose semantics (using outer_dims_perm attribute). We need a pattern that folds `linalg.transpose` op (and equivalent generic ops) into `tensor.pack` op. That will make graph simpler and help fusion.

E.g.,

```mlir
func.func @foo(%arg0: tensor<56x57x1x64xf32>) -> tensor<1x2x56x57x32xf32> {
  %0 = tensor.empty() : tensor<1x56x57x64xf32>
  %transposed = linalg.transpose
    ins(%arg0 : tensor<56x57x1x64xf32>)
    outs(%0 : tensor<1x56x57x64xf32>)
    permutation = [2, 0, 1, 3]
  %1 = tensor.empty() : tensor<1x2x56x57x32xf32>
  %pack = tensor.pack %transposed
    outer_dims_perm = [0, 3, 1, 2]
    inner_dims_pos = [3]
    inner_tiles = [32]
    into %1 : tensor<1x56x57x64xf32> -> tensor<1x2x56x57x32xf32>
  return %pack : tensor<1x2x56x57x32xf32>
}
```

can be lowered to

```mlir
func.func @foo(%arg0: tensor<56x57x1x64xf32>) -> tensor<1x2x56x57x32xf32> {
  %0 = tensor.empty() : tensor<1x2x56x57x32xf32>
  %pack = tensor.pack %arg0
    outer_dims_perm = [2, 3, 0, 1]
    inner_dims_pos = [3]
    inner_tiles = [32]
    into %0 : tensor<56x57x1x64xf32> -> tensor<1x2x56x57x32xf32>
  return %pack : tensor<1x2x56x57x32xf32>
}
```

Same for `(tensor.unpack, linalg.transpose)` pair, we need a pattern to fold the pair into a single `tensor.unpack` op.

```[tasklist]
### Tasks
- [x] Fold pack + transpose -> pack
- [x] Fold transpose + pack -> pack
- [x] Fold unpack + transpose -> unpack
- [x] Fold transpose + unpack -> unpack
```

**Comment by hanhanW** [comment]
@Shukla-Gaurav we can discuss this after you finish https://github.com/openxla/iree/issues/15314

**Comment by meshtag** [comment]
I would like to work on this if there is no conflicting work and no strict deadline for the completion (I'll be doing this in my free time). 

I have two questions: 
1. Do we fold in cases where `tensor.pack` is done first followed by `linalg.transpose` (assuming the latter is the only user of the former)?
2.  If there are multiple uses of the output of `linalg.transpose`, do we fold for cases where a `tensor.pack` is an immediate consumer leaving all other cases untouched where a `tensor.pack` is not the consumer (this would mean that the original `linalg.transpose` op will still be present for remaining uses)? 

PS: After an initial look at the codebase, it seems that related lowering pattern(s) should go in [this file](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/DecomposePackUnPackOps.cpp), am I correct?

**Comment by hanhanW** [comment]
SGTM, thanks for volunteering the issue! We want to add the patterns to [FoldIntoPackAndUnpackPatterns.cpp](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Tensor/Transforms/FoldIntoPackAndUnpackPatterns.cpp). We need a separate method. It populates the patterns that folds transpose ops into pack and unpack ops. Then we use it in IREE.

> Do we fold in cases where tensor.pack is done first followed by linalg.transpose (assuming the latter is the only user of the former)?

Yes, we will need both. Also, we want to fold `linalg.generic` ops into pack/unpack ops if they are just transpose ops.

> If there are multiple uses of the output of linalg.transpose, do we fold for cases where a tensor.pack is an immediate consumer leaving all other cases untouched where a tensor.pack is not the consumer (this would mean that the original linalg.transpose op will still be present for remaining uses)?

We need the folding for all the cases, even if transpose ops have other consumers. It gives us a cleaner graph, which should help fusion analysis in IREE. (It can be controllable with a callback, but I don't see the need at this moment.)

**Comment by meshtag** [comment]
I have created a [first draft pull request ](https://github.com/llvm/llvm-project/pull/74206) for the cases involving `linalg.transpose` and `tensor.pack`. I would prefer handling other cases in separate commit (s) once we agree on and/or land the current patch.

**Comment by meshtag** [comment]
In cases where `linalg.transpose` is done after `tensor.pack`, it is possible that `linalg.transpose` is changing the permutation of inner tile dimensions. How do we fold this in `tensor.pack`? Since we can only change permutation of non-tiled dimensions in `tensor.pack` via attribute `outer_dims_perm`.

**Comment by qedawkins** [comment]
> In cases where `linalg.transpose` is done after `tensor.pack`, it is possible that `linalg.transpose` is changing the permutation of inner tile dimensions. How do we fold this in `tensor.pack`? Since we can only change permutation of non-tiled dimensions in `tensor.pack` via attribute `outer_dims_perm`.

`inner_dims_pos` allows specifying the order of the inner tiles which should be what you're looking for. If it's transposing inner tile dimensions with outer tile dimensions that's not possible to fold though.

**Comment by meshtag** [comment]
> inner_dims_pos allows specifying the order of the inner tiles which should be what you're looking for. 

From what I understand, `inner_dims_pos` would specify which dimensions to use for tiling the tensor with sizes specified by `inner_tiles`. But the ordering of inner tile dimensions would still be the same, right? 

For ex. 
1. `inner_tiles = [16, 32]` and `inner_dims_pos = [0, 1]` would result in 0th dimension being tiled by 16 and 1st dimension being tiled by 32, with the output vector having its shape as `...x16x32`
2.  `inner_tiles = [16, 32]` and `inner_dims_pos = [1, 0]` would result in 0th dimension being tiled by 32 and 1st dimension being tiled by 16, with the output vector having its shape as `...x16x32`

Note that the output vector shape was the same in both cases, so is there a way for us to transpose even among inner tile dimensions using `tensor.pack`? 

>   If it's transposing inner tile dimensions with outer tile dimensions that's not possible to fold though.

I agree. Do we try to add some kind of check in the pattern to detect if this is happening, and not fold it if that's the case?

**Comment by qedawkins** [comment]
> > inner_dims_pos allows specifying the order of the inner tiles which should be what you're looking for.
> 
> From what I understand, `inner_dims_pos` would specify which dimensions to use for tiling the tensor with sizes specified by `inner_tiles`. But the ordering of inner tile dimensions would still be the same, right?
> 
> For ex.
> 
>     1. `inner_tiles = [16, 32]` and `inner_dims_pos = [0, 1]` would result in 0th dimension being tiled by 16 and 1st dimension being tiled by 32, with the output vector having its shape as `...x16x32`
> 
>     2. `inner_tiles = [16, 32]` and `inner_dims_pos = [1, 0]` would result in 0th dimension being tiled by 32 and 1st dimension being tiled by 16, with the output vector having its shape as `...x16x32`
> 
> 
> Note that the output vector shape was the same in both cases, so is there a way for us to transpose even among inner tile dimensions using `tensor.pack`?

Right, so you need to transpose the `inner_tiles` as well (they map elementwise with the `inner_dims_pos`)
```
module {
  func.func @pack_nc_to_ncnc(%arg0: tensor<128x256xf32>, %arg1: tensor<4x16x32x16xf32>) -> tensor<4x16x32x16xf32> {
    %pack = tensor.pack %arg0 inner_dims_pos = [0, 1] inner_tiles = [32, 16] into %arg1 : tensor<128x256xf32> -> tensor<4x16x32x16xf32>
    return %pack : tensor<4x16x32x16xf32>
  }
}
```
becomes
```
module {
  func.func @pack_nc_to_ncnc(%arg0: tensor<128x256xf32>, %arg1: tensor<4x16x16x32xf32>) -> tensor<4x16x16x32xf32> {
    %pack = tensor.pack %arg0 inner_dims_pos = [1, 0] inner_tiles = [16, 32] into %arg1 : tensor<128x256xf32> -> tensor<4x16x16x32xf32>
    return %pack : tensor<4x16x16x32xf32>
  }
}
```

(I had to go re-verify how this works, the semantics of these ops are tricky)

> 
> > If it's transposing inner tile dimensions with outer tile dimensions that's not possible to fold though.
> 
> I agree. Do we try to add some kind of check in the pattern to detect if this is happening, and not fold it if that's the case?

Yes, you should make sure not to fold in such cases.

**Comment by hanhanW** [comment]
kindly ping, @meshtag are you still working on the issue? If not, maybe I can find someone to work on it.

**Comment by meshtag** [comment]
I am not getting much time these days. I think it's better if someone else takes over from here. Thanks!

**Comment by hanhanW** [comment]
I'm seeing the below pattern from @bjacob's PR, so we need to prioritize the issue now. @pashu123 would you be able to help on this ? We already have pack patterns (thanks to @meshtag ), and we will need the unpack patterns soon. The patterns should be added to the [upstream PackAndUnpackPatterns.cpp file](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Tensor/Transforms/PackAndUnpackPatterns.cpp). I can fill you in more context through VC if needed.

```mlir
    %transposed = linalg.transpose ins(%14 : tensor<1x?x4x16xi32>) outs(%15 : tensor<?x1x16x4xi32>) permutation = [1, 0, 3, 2] 
    %16 = tensor.empty(%5) : tensor<?x4xi32>
    %unpack = tensor.unpack %transposed outer_dims_perm = [0, 1] inner_dims_pos = [0, 1] inner_tiles = [16, 4] into %16 : tensor<?x1x16x4xi32> -> tensor<?x4xi32>
```

**Comment by pashu123** [comment]
> I'm seeing the below pattern from @bjacob's PR, so we need to prioritize the issue now. @pashu123 would you be able to help on this ? We already have pack patterns (thanks to @meshtag ), and we will need the unpack patterns soon. The patterns should be added to the [upstream PackAndUnpackPatterns.cpp file](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Tensor/Transforms/PackAndUnpackPatterns.cpp). I can fill you in more context through VC if needed.
> 
> ```mlir
>     %transposed = linalg.transpose ins(%14 : tensor<1x?x4x16xi32>) outs(%15 : tensor<?x1x16x4xi32>) permutation = [1, 0, 3, 2] 
>     %16 = tensor.empty(%5) : tensor<?x4xi32>
>     %unpack = tensor.unpack %transposed outer_dims_perm = [0, 1] inner_dims_pos = [0, 1] inner_tiles = [16, 4] into %16 : tensor<?x1x16x4xi32> -> tensor<?x4xi32>
> ```



> I'm seeing the below pattern from @bjacob's PR, so we need to prioritize the issue now. @pashu123 would you be able to help on this ? We already have pack patterns (thanks to @meshtag ), and we will need the unpack patterns soon. The patterns should be added to the [upstream PackAndUnpackPatterns.cpp file](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Tensor/Transforms/PackAndUnpackPatterns.cpp). I can fill you in more context through VC if needed.
> 
> ```mlir
>     %transposed = linalg.transpose ins(%14 : tensor<1x?x4x16xi32>) outs(%15 : tensor<?x1x16x4xi32>) permutation = [1, 0, 3, 2] 
>     %16 = tensor.empty(%5) : tensor<?x4xi32>
>     %unpack = tensor.unpack %transposed outer_dims_perm = [0, 1] inner_dims_pos = [0, 1] inner_tiles = [16, 4] into %16 : tensor<?x1x16x4xi32> -> tensor<?x4xi32>
> ```

I will start working on this. Thanks.

**Comment by bjacob** [comment]
Good catch @hanhanW and thanks in advance @pashu123 !

**Comment by pashu123** [comment]
Added here: https://github.com/llvm/llvm-project/commit/aa7ae1ba0bfc3421cc933c9d0e236e5f642d23ac @hanhanW All four tasks are completed; let's close the issue.
