### ISSUE TITLE
[EPIC][DT] Have better data-tiling coverage and program graph

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15604]
Creating this issue to track how we get better coverage and graph for data-tiling. The issues are sorted by priority:

```[tasklist]
### Tasks
- [ ] https://github.com/openxla/iree/issues/15314
- [ ] https://github.com/openxla/iree/issues/15027
- [ ] https://github.com/openxla/iree/issues/15367
- [ ] https://github.com/openxla/iree/issues/15417
```
