### ISSUE TITLE
[EPIC][CPU] int4 sub-type emulation

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15613]
Creating an EPIC issue for tracking emulation support on CPU side. We should have full coverage on CPU side if we clear below tasks. @Max191 has been making good progress on this.

```[tasklist]
### Tasks
- [ ] https://github.com/openxla/iree/issues/15370
- [ ] https://github.com/openxla/iree/issues/15515
- [ ] https://github.com/openxla/iree/issues/15540
- [x] Missing emulation support for memref.reinterpret_cast -- https://github.com/llvm/llvm-project/pull/73144
- [ ] https://github.com/openxla/iree/issues/15575
- [ ] https://github.com/openxla/iree/issues/15369
```
