### ISSUE TITLE
[EPIC][CPU] Increase op coverage for data-tiling path

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#15640]
We have supported set encodings on matmul and batch_matmul, and get them data-tiled. For matvec/vecmat cases, we now expand shapes and leverage it to `[batch_]matmul` cases. This epic tracks that how we increase the op coverage for data-tiling path. After clears the below tasks, we are able to set encoding on all the matmul-like ops.

```[tasklist]
### Tasks
- [ ] https://github.com/openxla/iree/issues/15641
- [ ] https://github.com/openxla/iree/issues/15643
- [ ] https://github.com/openxla/iree/issues/15373
```

**Comment by hanhanW** [comment]
Closing the EPIC issue because we already reach to the state.
