### ISSUE TITLE
[Epic] HIP HAL driver rewrite

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#15790]
### Background 

The current ROCm HAL driver was based on the initial CUDA HAL driver; both are prototypes in the early days. We are in the process of rewriting the CUDA HAL driver, tracked in https://github.com/openxla/iree/issues/13245, to fix various issues listed there. The ROCm HAL inherits similar issues and needs to be rewritten too. This is the tracking epic for this effort.

### Goals and Plans
The goals to achieve are similar to the CUDA HAL driver rewrite, listed in https://github.com/openxla/iree/issues/13245. The overall plan is to start a new experimental HAL driver in [experiemental/](https://github.com/openxla/iree/tree/main/experimental), `hip`, and leverage corresponding pieces in `cuda2` there to bring up.

Along the way, we want to flesh out CTS https://github.com/openxla/iree/issues/13250.

### Concrete Tasks

These are major abstract tasks now; as we go we'll break them down into smaller ones and create seprate task list to track.

```[tasklist]
### Basics
- [ ] https://github.com/openxla/iree/pull/15506
- [ ] https://github.com/openxla/iree/pull/15887
```

```[tasklist]
### Memory Management
- [ ] https://github.com/openxla/iree/pull/15791
```

```[tasklist]
### Compute Pipeline
- [ ] https://github.com/openxla/iree/pull/15910
- [ ] https://github.com/openxla/iree/pull/15937
- [ ] https://github.com/openxla/iree/pull/16290
- [ ] Enable graph command buffer with latest HIP API
```

```[tasklist]
### Synchronization
- [ ] https://github.com/openxla/iree/pull/16305
```

```[tasklist]
### Collectives
- [ ] Support collective APIs
```
```[tasklist]
### HAL conformance testing suite
- [ ] https://github.com/openxla/iree/pull/16380
```
