### ISSUE TITLE
[EPIC][CPU] Generate efficient vectorized pack op for non-f32 types.

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#16314]
This is the EPIC that collects pack optimization work. We should generate vectorized code (without stack allocation) after finishing below tasks.

### Tasks
- [ ] https://github.com/iree-org/iree/issues/15600
- [ ] https://github.com/iree-org/iree/pull/16213
- [ ] https://github.com/iree-org/iree/issues/16313
- [ ] https://github.com/iree-org/iree/issues/15441
- [ ] https://github.com/iree-org/iree/issues/16071
- [ ] Deprecate DecomposePackUnPackOps pass

cc @dcaballe @bjacob @Max191 @MaheshRavishankar This collects the issues I've seen for pack op codegen. The LHS and RHS have different issues. Some of the prototype and ideas are updated in the child issues.

**Comment by dcaballe** [comment]
SG! I still have some doubts about using direct vectorization here but I'm ok to move forward with it. We should also work on efficient pack/unpack support for targets without masking support (e.g., Neon). Currently, I'm seeing if/else statements/scalar code for it.

**Comment by hanhanW** [comment]
> I still have some doubts about using direct vectorization here but I'm ok to move forward with it.

I think we are penalized by the current flow esp for pack_with_padding fusion cases. I need it, so I can evaluate how far we can push. Hopefully it will benefit all the CPUs.

> We should also work on efficient pack/unpack support for targets without masking support

It would be more efficient because you don't need to go with stack allocation. We might get some penalty on shape_cast lowering, but it is a better state to me. Let's see.

I'm not going to "flip it anyway", but it unblocks me to prototype more things. We might get diverge for different CPUs, but it open a new path for us. Let's see what we can do better here. :)
