### ISSUE TITLE
[Epic] Vector Distribution Framework

### ISSUE THREAD

**Issue by Groverkss** [iree-org/iree#16369]
This issue tracks progress on vector distribution framework.

```[tasklist]
### Layouts
- [ ] Add warp enum to LayoutV1
- [ ] https://github.com/openxla/iree/pull/16368
```

```[tasklist]
### Distribution Patterns
- [ ] Move transfer_read, transfer_write, broadcast distribution patterns to a GPUThreadInterface
- [ ] Move multi_reduction distribution to a GPUCrossThreadInterface
- [ ] Add subgroup level conflict distribution (lowering to bpermute)
- [ ] Add workgroup level conflict distribution (read/write to shared memory)
- [ ] https://github.com/openxla/iree/pull/16379
```

```[tasklist]
### Distribution Framework
- [ ] Move VectorExt to Codegen/Dialect/Distribution
- [ ] https://github.com/openxla/iree/issues/16307
- [ ] https://github.com/openxla/iree/issues/16308
- [ ] https://github.com/openxla/iree/issues/16119
```

```[tasklist]
### Distribution Analysis
- [ ] Move conflict resolution out of layout analysis
- [ ] Add in IR constructs to represent layout anchors to allow decisions to be made earlier (for example pre-bufferization)
```

```[tasklist]
### Future Exploration
- [ ] Explicit layout attributes in a DistributedVector type upstream
- [ ] https://github.com/openxla/iree/issues/16127
```

**Comment by Groverkss** [comment]
Most of these were done / are stale
