### ISSUE TITLE
Tracy with internalized Capstone 6

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#16777]
# Context

[Tracy](https://github.com/wolfpld/tracy) has an external dependency on [Capstone](https://github.com/capstone-engine/capstone) for disassembly.

Only the current development branch of capstone, named [next](https://github.com/capstone-engine/capstone/tree/next), is recent enough for our purposes, ans we in IREE are living on the cutting edge of new SIMD ISA extensions. Its version number is 6, so we currently want Capstone 6, but by the time it becomes stable we'll probably want Capstone 7, etc. We want the cutting edge.

That has been a problem for IREE users with Tracy, requiring custom [documentation](https://github.com/openxla/iree/blob/main/docs/website/docs/developers/performance/profiling-with-tracy.md#do-you-need-capstone-next). Compounding that, Capstone has recently done a breaking renaming, requiring patching Tracy: https://github.com/wolfpld/tracy/pull/671 .

Now on the latter Tracy PR the discussion has mentioned that another Tracy PR https://github.com/wolfpld/tracy/pull/707 is about to internalize Tracy as a [CPM.cmake](https://github.com/cpm-cmake/CPM.cmake) package. I don't know any specifics of CPM.cmake, but that shouldn't matter too much for us since we are carrying our own Tracy CMake setup anyway: https://github.com/openxla/iree/blob/main/build_tools/third_party/tracy/CMakeLists.txt

So once Tracy has internalized a version of Capstone (currently 5.0.1), we could do a Tracy bump on our side, also internalizing the same version of Capstone in whichever way works for us; and then as a second step from there, we could work with Tracy upstream on a Capstone 5->6 bump, the Tracy-side code changes being as in https://github.com/wolfpld/tracy/pull/671 or the simpler macro-expansion of that since, being internalized, now we wouldn't have to worry about compatibility with other Capstone versions anymore.

# Steps

```[tasklist]
### Tasks
- [ ] Wait for https://github.com/wolfpld/tracy/pull/707 to be merged.
- [ ] Bump Tracy, internalize the same Capstone 5 version in our own way.
- [ ] Work on a Tracy-side bump of its Capstone version from 5 to 6, as in https://github.com/wolfpld/tracy/pull/671.
- [ ] Bump Tracy again and simultaneously bump Capstone to 6.
```

**Comment by ScottTodd** [comment]
Tracy has been updated in IREE. Let's update the capstone version upstream and then update again?

**Comment by ScottTodd** [comment]
Fixed by https://github.com/iree-org/iree/pull/19842
