### ISSUE TITLE
[EPIC][CPU] Enable direct pack/unpack vectorization in IREE

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#16948]
This collects the tasks to enable direct pack/unpack vectorization by default.

### Tasks
- [x] Land https://github.com/iree-org/iree/pull/16692
- [x] Finish vector input sizes inference from IR for pack op. https://github.com/openxla/iree/pull/16629
- [x] Finish vector input sizes inference from IR for unpack op. https://github.com/openxla/iree/pull/16664
- [x] https://github.com/openxla/iree/issues/16975
- [x] https://github.com/openxla/iree/issues/16979
- [x] Deprecate DecomposePackUnPackOps pass. I.e., land https://github.com/openxla/iree/pull/16672/commits/e7641c75209605debd8fe69914e3a9fc74c44b9b

**Comment by hanhanW** [comment]
The two prototypes I have for pack/unpack shape inference are https://github.com/openxla/iree/pull/16629 and https://github.com/openxla/iree/pull/16664

**Comment by hanhanW** [comment]
Closing the issue because all the tasks are cleared.
