### ISSUE TITLE
[EPIC][GPU][DT] Bring up GPU data-tiling with reasonable performance

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#17181]
## Overview

This is the umbrella issue that collects tasks toward phase 1. In the phase 1, we aim to provide a functional data-tiling GPU path with reasonable performance. In this phase, we don't chase for optimal performance. Instead, we want to enable the path for all e2e tracking models.

The reasonable performance means that we should be able to vectorize, and apply vector distribution on data-tiling ops (i.e., pack/unpack/mmt4d-like ops).

ETA: ~1 month

## Milestone 1 - enable data-tiling in tests/e2e/matmul test suite

The scope is to compile and execute a linalg.matmul; enable e2e tests. Additionally, we want to extract few matmul ops (potentially with dequant ops) from sdxl and lamma models, and focus on them. To achieve the milestone, the major tasks are:

- [x] https://github.com/iree-org/iree/issues/17191
- [x] https://github.com/iree-org/iree/issues/17185
- [x] https://github.com/iree-org/iree/issues/17186
- [x] https://github.com/iree-org/iree/issues/17187
- [x] https://github.com/iree-org/iree/issues/17188
- [x] https://github.com/iree-org/iree/issues/17189

@bjacob let's share the above tasks between you and me. I'll convert the tasks into issues soon.

## Milestone 2 - enable at least one e2e model on benchmark CI

This milestone mainly focus on fusion codegen, which allows us to compile and execute ML workloads. For now, the target is sdxl and sd3.

Major tasks:

- [x] Support tiling interface to fuse consumers
- [x] Build the pipeline for pack fusion using "tile produce and fuse consumer" approach.
- [x] Be able to codegen unpack fusion.
- [ ] Enable sdxl/sd3 models on e2e benchmark suite.

Assign @MaheshRavishankar to be contact point for milestone 2, because he is tracking the [TilingInterface support](https://discourse.llvm.org/t/rfc-tiling-interface-supports-fuse-consumer/76286). I can jump into some tasks when there is a need.

**Comment by hanhanW** [comment]
(cc @qedawkins @antiagainst @powderluv @stellaraccident )

**Comment by hanhanW** [comment]
@bjacob I volunteer you to be assigned for https://github.com/iree-org/iree/issues/17185 and https://github.com/iree-org/iree/issues/17188 for now, but feel free to pick whatever tasks that you're interested in. Also, feel free to update the issues because I could miss something. I'll pick up the pack/unpack codegen because I had some patches long long long time ago; I'll try to revamp them.

**Comment by hanhanW** [comment]
Most tasks are done, and we are looking at perf gap for llama and sdxl now. Closing the issue because there are no action items. The future work is tracked in https://github.com/orgs/iree-org/projects/17
