### ISSUE TITLE
Support for MLIR based μkernels on GPU backends

### ISSUE THREAD

**Issue by qedawkins** [iree-org/iree#17788]
# Overview

With progress on MLIR based kernel generators like [tkf](https://github.com/nod-ai/SHARK-Turbine/tree/tkf?tab=readme-ov-file) (this might be an out of date link), we have an opportunity to flesh out a μkernel path for GPU backends like SPIR-V and ROCm which currently don't have compilers/tools for generating the core implementation of a μkernel that can keep up with our needs.

Currently [tkf](https://github.com/nod-ai/SHARK-Turbine/tree/tkf?tab=readme-ov-file) is capable of generating full kernels as Stream executables that are emitted by a front end either on model export or later inserted with a manual match and replace. This limits the fusion capabilities of the compiler or requires involved match + replace at the frontend or of Flow executables.

## MLIR μkernels

Existing μkernels for LLVMCPU (and a few examples for CUDA and ROCm) are based on LLVM bitcode generated externally and linked in Codegen when lowering to LLVM. After various levels of outer loop tiling, operations with μkernel implementations are matched and replaced with [ukernel.generic](https://github.com/iree-org/iree/blob/d7884011f71fbd1d2f4a7ecfeb4fe372bde728e8/compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/UKernelOps.td#L27). A writeup of the flow can be found [here](https://iree.dev/community/blog/2024-01-22-exploring-cpu-microkernels-on-a-matmul-example/#overview-of-the-compilation-and-linking-flow).

The difference with MLIR based μkernels like the ones tkf can generate is that we do not need to link at the LLVM level instead we can essentially treat a library of MLIR based μkernels simply as a second external module, e.g.
```mlir
builtin.module @ukernels {
  func.func @matmul_transpose_b(%lhs: memref<64x64xi8>, %rhs: memref<64x64xi8>, %out: memref<64x64xi32>) {
    ...
  }
}
builtin.module {
  hal.executable {
    hal.executable.variant {
      // Any standard fused matmul_transpose_b dispatch
    }
  }
}
```
which can be treated the same as any other μkernel and linked at some point before lowering to LLVM/SPIR-V instead of after.

## GPU μkernels

GPU has another difference from CPU in that there are global kernel parameters that must be consistent between the μkernel and the full compiled executable, namely workgroup size and subgroup size. In codegen this ends up annotated on the TranslationInfo, so we will need to annotate the required workgroup size on the μkernel (function) and import that information during kernel config. This could looks something like the following:

```mlir
builtin.module @ukernels {
  func.func @matmul_transpose_b_ukernel(%lhs: memref<64x64xi8>, %rhs: memref<64x64xi8>, %out: memref<64x64xi32>)
    attributes {workgroup_size = [64, 2, 1], subgroup_size = 64} {
    ...
  }
}
builtin.module {
  hal.executable {
    hal.executable.variant {
      hal.executable.export @mmt
      module {
        func.func @mmt() attributes {
          translation_info = #iree_codegen.translation_info<LLVMGPUTileAndFuse, workgroup_size = [64, 2, 1], subgroup_size = 64
        } {
          ...
          linalg.matmul_transpose_b {lowering_config = #iree_gpu.lowering_config<{ukernel_name = "matmul_transpose_b_ukernel", workgroup = [64, 64], reduction = [0, 0, 64]}>
          ...
        }
      }
    }
  }
}
```

Kernels emitted by tkf tend to do complex pipelining/scheduling of the inner loop of the matmul, meaning in practice we may not opt to do reduction tiling as a part of codegen and rather emit the μkernel directly after tiling + distributing to workgroups. Because of this, μkernels will likely be mutually exclusive with fusion of matmul producers. For handling of fused consumers, we will likely need a small shared memory allocation at the boundary of the μkernel and the fused consumer, meaning the consumer will need its own lowering config.

### Tasks

- [ ] Add support in tkf for emitting memref functions that we can target μkernels with
- [ ] Add a pass for "linking" a μkernel in MLIR w/ memref + vector IR
- [ ] Add support to [KernelConfig](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp) for μkernels w/ additional configs on surrounding consumers
- [ ] Add a pass to analyze live ranges of workgroup allocations and reuse them (for reusing shared memory for the output)

## Future Flow level fusable μkernels

TODO: write this

**Comment by hanhanW** [comment]
Status update: I'm prototyping things in a remote branch: https://github.com/hanhanW/iree/tree/hanhan-mlir-based-ukernel

Now I'm able to match ops and inline the mlir functions. The next step is building the pipeline to properly tile and distribute the ops and rewrite it to `func.call`. I'll look at it tomorrow.

To repro, see https://github.com/hanhanW/iree/blob/hanhan-mlir-based-ukernel/samples/ukernel_module/example_matmul.mlir

**Comment by benvanik** [comment]
instead of `--iree-codegen-mlir-ukernel-file-name=%p/ukernel.mlir ` you'll need to use the `#hal.executable.objects` attributes. The attributes work correctly when multitargeting and handle both loading files and embedding files in IR.

(happy to chat more - but there's lots of helpers in there - `IREE::HAL::ExecutableObjectAttr::filterObjects` would let you pull out .mlir files to link earlier, etc)

**Comment by hanhanW** [comment]
`#hal.executable.objects` is quite new to me. I took a look at the description and usages in `samples`; I feel that it does not fit the needs. The attribute requires object file (which can be updated for sure), while we're looking for IRs at memref+vector level. The idea is to leverage the innermost code to tkf (which is using memref+vector+gpu_specific IRs); convert the linalg op with `func.call` at some moment. We still want to codegen the inlining IR (which is generated by tkf) because it is not at the object file level. E.g., https://github.com/hanhanW/iree/blob/hanhan-mlir-based-ukernel/samples/ukernel_module/ukernel.mlir

Do we use `#hal.executable.objects` in this context? So far, I'm following `transform_dialect/example_module.mlir` to build the path. Different from object files, it provides the lowering strategy for codegen and it works with tuning. The MLIR based ukernel seems to fit this path better.

https://github.com/iree-org/iree/blob/9ffe4735c8ed54a622e40b9a16df37657c0417b4/samples/transform_dialect/example_module.mlir#L119-L121

**Comment by benvanik** [comment]
The objects can be any form and are backend specific - they could be mlir in whatever dialect you want.

Don't use the transform dialect as inspiration - it's fundamentally incompatible with multitargeting and is not something we should be building core infrastructure on.

**Comment by hanhanW** [comment]
I see, I'll do more investigation tomorrow and bother you when I have questions. :)

**Comment by benvanik** [comment]
Please do! happy to chat :)

**Comment by qedawkins** [comment]
If there's a chat I'd like to listen in. If `hal.executable.objects` can do what we want, that would be perfect, but tests for it are a bit sparse so it's hard to tell. The v1 of this was scoped for ~this week alongside work needed on the tkf side, so I want to raise a flag for that. The final state we want isn't written up here (TODO to add support for injecting these things in the input) at which point `hal.executable.objects` will be what we want.

**Comment by benvanik** [comment]
At this point I think we all know that such shortcuts live long past any reasonable time horizon :)

Doing it with objects should be easier than rolling your own. In your codegen pass you get the `IREE::HAL::ExecutableVariantOp`, call `IREE::HAL::ExecutableObjectAttr::filterObjects(variantOp.getObjectAttrs(), {".vector.mlir"}, objectAttrs);` to get any relevant files, and walk them calling `objectAttr.loadData()` to get the contents in memory. `--iree-hal-executable-object-search-path=` sets the search path if you're specifying object files or you can embed the object data directly on the attributes. This will let you specify objects per dispatch all the way from frontends (if using `hal.dispatch.extern`), tag them on executables inserted via transform dialect, add them in codegen passes, etc.

The one helper that would be useful would be an `ExecutableVariantOp::consumeObjects` that filtered and then removed those filtered objects from the variant so that subsequent steps wouldn't see them. Something like:
```c++
void ExecutableVariantOp::consumeObjects(
    ArrayRef<StringRef> extensions,
    SmallVectorImpl<IREE::HAL::ExecutableObjectAttr> &filteredAttrs) {
  auto objectAttrs = getObjectsAttr();
  if (!objectAttrs) {
    return;
  }
  SmallVector<Attribute> remainingAttrs;
  for (auto objectAttr :
       objectAttrs.getAsRange<IREE::HAL::ExecutableObjectAttr>()) {
    auto path = objectAttr.getPath();
    auto ext = llvm::sys::path::extension(path);
    if (llvm::is_contained(extensions, ext)) {
      filteredAttrs.push_back(objectAttr);
    } else {
      remainingAttrs.push_back(objectAttr);
    }
  }
  if (remainingAttrs.size() != objectAttrs.size()) {
    setObjectsAttr(ArrayAttr::get(getContext(), remainingAttrs));
  }
}
```

then your linking pass just calls `variantOp.consumeObjects({".vector.mlir"}, objectAttrs);` and no-ops if the result is empty.

**Comment by qedawkins** [comment]
> This will let you specify objects per dispatch all the way from frontends (if using hal.dispatch.extern), tag them on executables inserted via transform dialect, add them in codegen passes, etc.

This issue is focused on the style of ukernels used on CPU today which matches an operation and replaces it in codegen. So the detail that was not obvious to me when looking at `hal.executable.objects` is how to get an object attribute to a dispatch without a `hal.dispatch.extern` (or otherwise pre-baked dispatch).

The other requirement is that we only load each object file a single time and reuse it (rather than each dispatch loading the full object == 1000+ times). I'm not familiar with the code, but is that what `--iree-hal-executable-object-search-path=` lets us do?

**Comment by benvanik** [comment]
Ouch - I'm worried that you may be diverging in a bad direction :)

You can put a `hal.executable.objects` attr on flow/stream executables. We could allow them to be propagated from attributes on flow.dispatch.region if we wanted, too.

Remember: we're building a multi-targeting compiler designed for complex models. That's a core goal. One-size-fits-all approaches that assume a single target with a single substitution for all dispatches is an anti-pattern. If the only way the mechanism as designed works is that you have global flags that apply to all dispatches even if they don't need the objects then it's not designed to fit the needs of the project. Fine for experiments in branches, but not for new tech debt that continues making it impossible to achieve multi-targeting.

**Comment by qedawkins** [comment]
> If the only way the mechanism as designed works is that you have global flags that apply to all dispatches even if they don't need the objects then it's not designed to fit the needs of the project.

I'm not sure I follow. The goal here is to do the same thing that CPU does with its ukernels, just with an earlier linking phase. There is Codegen work needed to make this work though. Once we come up with a ukernel we like, we plumb it in to the target backend the same way it's done on CPU, but that plumbing is non-trivial work for a developer to add a ukernel every time. `--iree-codegen-transform-dialect-library` is there as a developer flag to make certain work/experimentation easier. Would the same thing not be reasonable here?

Perhaps it would be better to chat to make sure we're not talking past each other.

**Comment by hanhanW** [comment]
The idea of `ExecutableObjectAttr` is very valid to me. The way I'm seeing this is that `--iree-codegen-*` flag provides a path to connect pieces end-to-end. It is not clear how things would look like, so it's scoped to the tasks listed in the issue. IIUC, we will be able to replace the `--iree-codegen-*` flag with `ExecutableObjectAttr`, but it takes some time. Using `ExecutableObjectAttr` is an optimization, and using a global flag is for quick experiments. Well.. it's not an optimization.. it is more like how it should work in IREE -- as a final state. Using a global flag unblocks the further development, and I will come back to it later. I meant either land it properly to IREE, or follow-up on the global flag deprecation.

(Honestly, how to connect things together using `ExecutableObjectAttr` is not clear to me. On the good side, it means that I can learn more from the work. :))

**Comment by benvanik** [comment]
Put "experimental" in the flag name and I won't complain anymore - we have _a lot_ of flags/behavior based on flags that have been added temporarily and are now load-bearing ;)

**Comment by hanhanW** [comment]
> Put "experimental" in the flag name and I won't complain anymore - we have _a lot_ of flags/behavior based on flags that have been added temporarily and are now load-bearing ;)

Good point. I also hope that people don't abuse these experimental flags in their workloads. They are really just for experimental development.

**Comment by qedawkins** [comment]
Maybe we set a precedent going forward that flags not exposed through the option bindings (i.e. floating llvm::cl globals) need an `experimental` or `dev` prefix? I bet it would help people use them a little more cautiously.

**Comment by benvanik** [comment]
That'd be awesome and short-circuit a lot of the "not the end state" concerns!

**Comment by hanhanW** [comment]
I finally get e2e prototype working in a hacky way... I'd like to discuss details in tomorrow's meeting.

Example Input:

```mlir
func.func @main(%lhs: tensor<2048x1280xf16>, %rhs: tensor<10240x1280xf16>) -> tensor<2048x10240xf32> {
  %cst = arith.constant 0.0 : f32
  %init = tensor.empty() : tensor<2048x10240xf32>
  %fill = linalg.fill ins(%cst : f32) outs(%init : tensor<2048x10240xf32>) -> tensor<2048x10240xf32>
  %gemm = linalg.matmul_transpose_b
    ins(%lhs, %rhs: tensor<2048x1280xf16>, tensor<10240x1280xf16>)
    outs(%fill : tensor<2048x10240xf32>)
    -> tensor<2048x10240xf32>
  return %gemm : tensor<2048x10240xf32>
}
// RUN: iree-compile %s --iree-hal-target-backends=rocm \
// RUN:   --iree-rocm-target-chip=gfx90a \
// RUN:   --iree-codegen-mlir-ukernel-file-name=%p/ukernel.mlir \
// RUN:   --compile-to=executable-targets \
// RUN:   --mlir-disable-threading | \
// RUN: FileCheck %s
// CHECK: llvm.func @matmul_transpose_b_ukernel
// CHECK: llvm.func @main
// CHECK: llvm.call @matmul_transpose_b_ukernel(
```

ukernel file:

```mlir
#map = affine_map<(d0, d1, d2) -> (d0, d2)>
#map1 = affine_map<(d0, d1, d2) -> (d1, d2)>
#map2 = affine_map<(d0, d1, d2) -> (d0, d1)>
#translation = #iree_codegen.translation_info<None workgroup_size = [128, 2, 1] subgroup_size = 64,
  {indexing_maps = [#map, #map1, #map2],
   loop_range = array<i64: 2048, 10240, 1280>,
   workgroup_tile_sizes = array<i64: 64, 128, 0>}>
module {
  func.func @matmul_transpose_b_ukernel(
      %arg0: memref<64x1280xf16, strided<[1280, 1], offset: ?>, #gpu.address_space<global>>,
      %arg1: memref<128x1280xf16, strided<[1280, 1], offset: ?>, #gpu.address_space<global>>,
      %arg2: memref<64x128xf32, strided<[10240, 1], offset: ?>, #gpu.address_space<global>>) attributes {translation_info = #translation} {
    linalg.matmul_transpose_b
      ins(%arg0, %arg1 : memref<64x1280xf16, strided<[1280, 1], offset: ?>, #gpu.address_space<global>>, memref<128x1280xf16, strided<[1280, 1], offset: ?>, #gpu.address_space<global>>)
      outs(%arg2 : memref<64x128xf32, strided<[10240, 1], offset: ?>, #gpu.address_space<global>>)
    return
  }
}
```


Selected IR dumps: https://gist.github.com/hanhanW/f8ae24b483fead4303dab67e6f950326
