### ISSUE TITLE
Refresh iree.dev documentation pages

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#18174]
Some pages have grown stale. I did a quick read through and here is a loosely organized list of updates we can make (keeping the existing structure and not making deeper changes):

## Home

- [ ] https://iree.dev/ add artwork / diagrams / other highlights to the initial landing page. Highlight example use cases (e.g. PyTorch --> Vulkan on Android, ONNX --> ROCm on Windows, could have an interactive diagram or animation) and key metrics (binary size, benchmark results, runtime overhead, operator set coverage)
- [x] https://iree.dev/ mention LF:AI
- [x] Add ONNX to project architecture diagram as an input (and maybe also GGUF?), maybe some mention of AIE in device code generation / runtime HALs?

## Building from source

- [ ] https://iree.dev/building-from-source/ should probably land on "getting started" with subcategories for cross-compilation, instead of having a mostly empty index page
- [ ] https://iree.dev/building-from-source/getting-started/ rework if/when optional components switch to default off
- [ ] https://iree.dev/building-from-source/getting-started/#using-the-python-bindings deemphasize TensorFlow
- [ ] https://iree.dev/building-from-source/android/ and other cross-compile pages - explain using python packages instead of a source compiler build (as the CI does now)

## Guides

- [x] https://iree.dev/guides/ add link to ONNX
- [ ] https://iree.dev/guides/ml-frameworks/ drop reference to stale iree-experimental repo?
- [ ] https://iree.dev/guides/ml-frameworks/#exportimport could use a diagram or sample (python source --> framework MLIR --> linalg MLIR)
- [ ] JAX: https://github.com/iree-org/iree/issues/5454 (see https://jax.readthedocs.io/en/latest/aot.html and https://jax.readthedocs.io/en/latest/export/export.html)
- [ ] https://iree.dev/guides/ml-frameworks/onnx/ add more colorful diagrams? Call out torch-mlir and torch more visibly? 
- [ ] https://iree.dev/guides/ml-frameworks/onnx/ include operator support table / latest test results for ops and models
- [x] https://iree.dev/guides/ml-frameworks/pytorch/ finish the migration from SHARK-Turbine to iree-turbine (https://github.com/iree-org/iree-turbine/issues/28)
- [x] https://iree.dev/guides/ml-frameworks/pytorch/ test with newer versions of PyTorch (not just `torch==2.3.0`)
- [x] https://iree.dev/guides/ml-frameworks/pytorch/ link to https://github.com/nod-ai/sharktank?
- [ ] https://iree.dev/guides/ml-frameworks/tensorflow/ add more concrete examples of usage
- [x] https://iree.dev/guides/ml-frameworks/tflite/ mention TOSA more prominently, replace the "Using Command Line Tools" section with something easier to follow that doesn't pin to the iree-model-artifacts bucket
- [x] https://iree.dev/guides/ml-frameworks/tflite/ mention compatible versions of tensorflow (need TOSA from a similar enough LLVM commit)
- [x] https://github.com/iree-org/iree/issues/17977 (including documenting mult-device support somewhere)
- [ ] drop tips about `PATH` env vars across pages
- [x] replace TensorFlow MobileNet example with something more recent / supported
- [x] https://iree.dev/guides/deployment-configurations/cpu/ mention Android less - focus on generality and mention platforms together (iOS, Android, Windows, Linux, macOS, etc.)
- [ ] https://iree.dev/guides/deployment-configurations/gpu-vulkan/ list specific versions and extensions required, and how to check for that
- [ ] https://iree.dev/guides/deployment-configurations/gpu-vulkan/ Rework how "SPIR-V" is introduced
- [x] https://iree.dev/guides/deployment-configurations/gpu-vulkan/ De-emphasize Android, mention all platforms together (mention MoltenVK? SwiftShader? Mesa?)
- [ ] https://iree.dev/guides/deployment-configurations/gpu-metal/ fill in content for this page
- [ ] https://iree.dev/guides/parameters/ document parameter importing

## Reference

- [x] https://iree.dev/reference/bindings/python/ mention iree-turbine for pytorch, drop iree-jax package name reference?
- [ ] https://github.com/iree-org/iree/issues/13483 merge TF and TFLite packages
- [x] https://iree.dev/reference/optimization-options/ add more options, link to tuner?
- [ ] https://iree.dev/reference/extensions/ move to developers section?
