### ISSUE TITLE
Llama dispatch perf tracking issue

### ISSUE THREAD

**Issue by IanWood1** [iree-org/iree#18853]
#### Issues/PRs
- [x] Fold `tensor.cast`s with `tensor.expand_shape` ops https://github.com/llvm/llvm-project/pull/112265
- [x] Bubble `tensor.expand_shape` ops through `tensor.collapse_shape` ops so they can be propagated further https://github.com/iree-org/iree/pull/18341
  - This one seems pretty important, its causing a lot of producer -> trunc ops to fail to be fused.
- [x] #18854
- [x] #18893
- [ ] https://github.com/iree-org/iree/pull/18103
- [x] https://github.com/iree-org/iree/issues/18956
  - For now, just disable data-tiling
- [x] https://github.com/iree-org/iree/issues/18954

#### Other:
- [ ] A bunch of slow_memcpys (especially initializers)

cc @MaheshRavishankar
