### ISSUE TITLE
Dramatically simplify our build configuration and get cmake install working (tracking issue)

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#3843]
Disaster-scale stuff here. We should be able to simplify things a lot. Let's work hard to not create death-by-a-thousand-papercuts by having a build that is as complex as some of the projects we are trying to replace.

* ~~[ ] #3817: expose a C API to the compiler~~ (not going to block this)
* [x] remove repo_utils.bzl
* [x] remove flatbuffers
  * [x] iree-dump-module
  * [x] hal compiler builders
  * [x] hal backend parsers
  * [x] vm compiler builder
    * [x] constant encoder
    * [x] bytecode module
  * [x] byte->ubyte in fbs (avoid signedness)
* [x] prune MSVC overrides/warnings to minimal set
* [x] sort copts/linkopts to allow defaults to be overridden
* [x] remove as many COPTS overrides as possible
  * [x] flatbuffers stuff
  * [x] VMA stuff
  * [x] -DVK_NO_PROTOTYPES
  * [x] -D_GNU_SOURCE
* [x] remove as many LINKOPTS overrides as possible
  * [x] -frameworks on metal HAL backend **should not be needed with #import? and -fcxx-modules**
  * [x] -ldl/-lpthread
* [x] remove PLATFORM_VULKAN_DEPS and PLATFORM_VULKAN_TEST_DEPS
* [x] rework most build/cmake files to simplify total target count (no globs tho)
  * [x] hal
  * [x] hal backends
  * [x] vm
* [x] remove IREE_COMMON_INCLUDE_DIRS
  * [x] usage for .td files
  * [x] usage for generated outputs/weird bundling stuff
  * [x] usage for third party files
* [x] kill alwayslink
  * [x] remove use from tblgen
  * [x] make HAL backend explicit
  * [x] remove iree/base/initializer.h
  * [x] remove iree_api_init
  * [x] remove bazel/cmake alwayslink support
* [x] remove iree::InitializeEnvironment
  * [ ] ~~#3814: may need to drop abseil flags for this~~
* [ ] fix iree/base/tracing rule to be bazel-to-cmake compatible
* [x] multipy/etc simplification/isolation? (may just need [this](https://github.com/EthicalML/vulkan-kompute/blob/master/python/CMakeLists.txt#L3))
* [x] #3842: remove sdl2/dear_imgui deps and build config
  * [x] remove bazel overlays for both and build guis as cmake-only
  * [x] drop sdl2 submodule and use cmake find_package instead
  * [ ] ~~delete gui sample using imgui (or move to experimental)~~
  * [x] drop imgui submodule
* [x] remove llvmjit runtime driver
  * [x] first need to ensure all tests can use aot/dylib
  * [x] ensure that runtime has zero transitive deps on llvm/mlir (https://github.com/google/iree/issues/4155)
* [x] #3848: continue excising abseil parts from core
  * [x] abseil headers exposed in our API (sometimes through things like absl/base/thread_annotations.h and stuff) are the highest priority to eliminate
* [x] remove IREE_MLIR_DEP_MODE
* [ ] signature_mangler; rename to iree/compat/tf/tf_signature_mangler or whatever and clean up attrs API later
* [x] rework cross-compilation to be standard cmake as much as possible (https://github.com/google/iree/issues/4323)
* [x] move cmake add all subdirs to macros
* [x] add a well-documented top-level cmake options file
* [x] make iree/base/main.h c, add flags parsing
* [x] move the random ass iree/tools/init_* files to where they belong in iree/compiler/
* [x] #3814: flags
* [x] #2843: logging

more to come

**Comment by GMNGeoffrey** [comment]
What is left to be done here?

**Comment by benvanik** [comment]
Mostly done!
![image](https://user-images.githubusercontent.com/75337/176820297-2891f808-dcf0-4443-9fde-c42e97353ee9.png)
